-- Student section content (Student plan, 7 ₼): scholarships and universities.
-- Researched September 2026 from the official pages linked in each row.
-- Fees and deadlines change every year: check the official page before relying on them.
-- Run in Supabase: SQL Editor → paste → Run (after supabase/app.sql). Safe to re-run:
-- rows are matched by name and updated.

create unique index if not exists scholarships_name_key on public.scholarships (name);
create unique index if not exists universities_name_key on public.universities (name);

insert into public.scholarships (name, provider, country, levels, fields, coverage, deadline, deadline_note, eligibility, how_to_apply, url, sort)
values
  ('Chevening', 'Böyük Britaniya hökuməti (FCDO)', 'Böyük Britaniya', array['master']::text[], '{}'::text[], 'Tam təqaüd: təhsil haqqı, aylıq yaşayış müavinəti, gediş-dönüş biletləri, viza xərcləri.', '2026-10-06'::date, '2027/28 tədris ili üçün: 6 oktyabr 2026, 11:00 UTC. Müraciət adətən avqustda açılır.', 'Azərbaycan vətəndaşı; bakalavr dərəcəsi; ən azı 2 il iş təcrübəsi; təhsildən sonra ən azı 2 il Azərbaycana qayıtmaq öhdəliyi. Böyük Britaniyada 3 magistr proqramına müraciət etmək lazımdır.', 'chevening.org-da onlayn forma: liderlik, şəbəkə qurma, “niyə UK” və karyera planı haqqında esselər, 2 tövsiyə. Seçilənlər Bakıda müsahibəyə çağırılır.', 'https://www.chevening.org/scholarship/azerbaijan/', 10),
  ('Fulbright Foreign Student Program', 'ABŞ Dövlət Departamenti', 'ABŞ', array['master']::text[], '{}'::text[], 'Təhsil haqqı, aylıq yaşayış təqaüdü, tibbi sığorta və beynəlxalq uçuş.', null::date, 'Hər il ABŞ-ın Bakıdakı səfirliyi elan edir (hazırda 2027–2028 tədris ili üçün müsabiqə).', 'Azərbaycan vətəndaşı; bakalavr dərəcəsi; güclü ingilis dili. Klinik ixtisaslar (tibb, stomatologiya, əczaçılıq, tibb bacısı) uyğun deyil; ictimai səhiyyə mümkündür.', 'Səfirliyin elanındakı onlayn forma, esselər və tövsiyələr; sonra imtahanlar (TOEFL, GRE) və müsahibə.', 'https://az.usembassy.gov/fulbright-foreign-student-program/', 20),
  ('Stipendium Hungaricum', 'Macarıstan hökuməti', 'Macarıstan', array['bachelor', 'master', 'phd']::text[], '{}'::text[], 'Pulsuz təhsil, aylıq təqaüd, yataqxana və ya yaşayış dəstəyi, tibbi sığorta.', null::date, 'Adətən noyabrda açılır, yanvarın ortasında bağlanır (2026/27 dövrü: 15 yanvar 2026).', 'Azərbaycan tərəfdaş ölkədir. Hər ölkə üçün icazə verilən səviyyə və sahələr ikitərəfli sazişlə müəyyən olunur; Azərbaycandakı göndərən tərəfin təsdiqi lazımdır.', 'stipendiumhungaricum.hu portalında müraciət, 2 proqrama qədər seçim; sonra universitetin qəbul imtahanı/müsahibəsi.', 'https://stipendiumhungaricum.hu/country/azerbaijan/', 30),
  ('Türkiye Bursları', 'Türkiyə hökuməti', 'Türkiyə', array['bachelor', 'master', 'phd']::text[], '{}'::text[], 'Təhsil haqqı, aylıq təqaüd, yataqxana, tibbi sığorta, bir dəfəlik gediş-dönüş bileti və 1 illik türk dili kursu.', null::date, 'Adətən yanvar–fevral (2026 dövrü: 10 yanvar – 25 fevral, uzadılmış tarix).', 'Yaş həddi: bakalavr üçün 21, magistr üçün 30, doktorantura üçün 35 yaşdan kiçik; minimum qiymət tələbləri var.', 'turkiyeburslari.gov.tr-də pulsuz onlayn müraciət, bir neçə universitet/proqram seçimi, sonra müsahibə.', 'https://www.turkiyeburslari.gov.tr/', 40),
  ('Global Korea Scholarship (GKS)', 'Koreya hökuməti (NIIED)', 'Cənubi Koreya', array['bachelor', 'master', 'phd']::text[], '{}'::text[], 'Təhsil haqqı, aylıq təqaüd, uçuş, tibbi sığorta və 1 illik Koreya dili kursu.', null::date, 'Magistr/doktorantura: adətən fevral–mart; bakalavr: adətən sentyabr–oktyabr. Səfirlik və universitet yolu var.', 'Azərbaycan vətəndaşları müraciət edə bilər. Magistr/doktorantura üçün 40 yaşdan kiçik; bakalavr üçün 25 yaşdan kiçik.', 'Study in Korea saytındakı elana əsasən səfirlik və ya birbaşa universitet vasitəsilə sənəd təqdimi.', 'https://www.studyinkorea.go.kr/', 50),
  ('Swedish Institute Scholarships for Global Professionals', 'İsveç İnstitutu', 'İsveç', array['master']::text[], '{}'::text[], 'Təhsil haqqı, aylıq yaşayış xərci, sığorta və səyahət qrantı (Azərbaycan üçün 10 000 SEK).', null::date, 'Adətən fevralda (əvvəlcə İsveç universitetinə müraciət etmək lazımdır).', 'Azərbaycan uyğun ölkələrdəndir. İş təcrübəsinin rəsmi sübutu tələb olunur (Azərbaycan üçün minimum saat həddi yoxdur); liderlik təcrübəsi qiymətləndirilir.', 'universityadmissions.se-də magistr proqramına müraciət, sonra si.se-də təqaüd müraciəti.', 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/', 60),
  ('DAAD təqaüdləri', 'Almaniya Akademik Mübadilə Xidməti (DAAD)', 'Almaniya', array['master', 'phd']::text[], '{}'::text[], 'Aylıq təqaüd, tibbi sığorta, səyahət müavinəti; proqramdan asılı olaraq digər xərclər.', null::date, 'Proqramdan asılıdır — çox vaxt təhsildən təxminən bir il əvvəl (payız aylarında).', 'Proqramdan asılıdır. Məs. EPOS (inkişafla bağlı magistr proqramları) adətən ən azı 2 il iş təcrübəsi istəyir.', 'DAAD təqaüd bazasında ölkə olaraq Azərbaycanı seç və sənə uyğun proqramın şərtlərinə bax.', 'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/', 70),
  ('Erasmus Mundus Joint Masters', 'Avropa İttifaqı', 'Avropa (bir neçə ölkə)', array['master']::text[], '{}'::text[], 'Tam təqaüd: təhsil haqqı, səyahət və aylıq müavinət; təhsil ən azı 2 Avropa ölkəsində keçir.', null::date, 'Hər proqramın öz son tarixi var, adətən dekabr–fevral.', 'Bütün ölkələrin vətəndaşları; bakalavr dərəcəsi; proqramın öz tələbləri (dil, sahə).', 'Erasmus Mundus kataloqundan proqram seç və birbaşa proqramın konsorsiumuna müraciət et.', 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en', 80),
  ('Xaricdə təhsil üzrə Dövlət Proqramı', 'Azərbaycan Respublikası Elm və Təhsil Nazirliyi', 'Azərbaycan (xaricdə təhsil)', array['bachelor', 'master']::text[], array['cs', 'engineering', 'science', 'medicine', 'education', 'business', 'arts', 'social']::text[], 'Nüfuzlu xarici universitetdə təhsil xərcləri Dövlət Proqramı çərçivəsində qarşılanır (şərtlər proqram qaydalarındadır).', null::date, 'Sənəd qəbulu hər tədris ili üçün ayrıca elan olunur.', 'Azərbaycan vətəndaşı; siyahıdakı nüfuzlu xarici universitetə qəbul (və ya orada təhsil); 15 prioritet ixtisas sahəsi (İT, mühəndislik, statistika, səhiyyə, təhsil, enerji, iqtisadiyyat və s.). Yerlərin ən azı 80%-i magistr üçündür. Məzun olduqdan sonra öhdəliklər var — qaydaları diqqətlə oxu.', 'Nazirliyin elektron sistemində “Şəxsi kabinet” yaradıb sənədləri yükləmək; uyğun namizədlər müsahibəyə çağırılır.', 'https://edu.gov.az/az/2022-2026-ci-iller-uzre-dovlet-proqrami/2022-2026-ci-iller-uzre-dovlet-proqrami2483', 90),
  ('MEXT (Yaponiya hökuməti təqaüdü)', 'Yaponiya Təhsil Nazirliyi', 'Yaponiya', array['bachelor', 'master', 'phd']::text[], '{}'::text[], 'Təhsil haqqı, aylıq təqaüd, gediş-dönüş bileti.', null::date, 'Səfirlik yolu: adətən yazda Yaponiyanın Azərbaycandakı səfirliyi elan edir.', 'Səviyyəyə görə yaş həddi; yazılı imtahan və müsahibə.', 'Səfirliyin elanına əsasən sənədlər, sonra imtahan və müsahibə; universitet yolu da mövcuddur.', 'https://www.studyinjapan.go.jp/en/', 100),
  ('Çin hökuməti təqaüdü (CSC)', 'China Scholarship Council', 'Çin', array['bachelor', 'master', 'phd']::text[], '{}'::text[], 'Tam təqaüd: təhsil haqqı, yataqxana, aylıq təqaüd, tibbi sığorta.', null::date, 'Adətən yanvar–aprel, universitet və ya səfirlik vasitəsilə.', 'Səviyyəyə görə yaş həddi; universitetin qəbul tələbləri.', 'Campus China portalında onlayn müraciət və seçilmiş universitetin tələbləri.', 'https://www.campuschina.org/', 110),
  ('Eiffel Excellence Scholarship', 'Fransa Xarici İşlər Nazirliyi (Campus France)', 'Fransa', array['master', 'phd']::text[], array['law', 'business', 'engineering', 'science', 'social']::text[], 'Aylıq müavinət, səyahət, tibbi sığorta və mədəni tədbirlər.', null::date, 'Namizədi fransız universiteti irəli sürür, adətən yanvarda.', 'Hüquq, iqtisadiyyat və idarəetmə, siyasi elmlər, mühəndislik və elm sahələrində magistr/doktorantura namizədləri.', 'Əvvəlcə fransız universitetinə müraciət et; universitet səni Eiffel proqramına namizəd kimi təqdim edir.', 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence', 120)
on conflict (name) do update set
  provider = excluded.provider, country = excluded.country, levels = excluded.levels, fields = excluded.fields,
  coverage = excluded.coverage, deadline = excluded.deadline, deadline_note = excluded.deadline_note,
  eligibility = excluded.eligibility, how_to_apply = excluded.how_to_apply, url = excluded.url, sort = excluded.sort, updated_at = now();

insert into public.universities (name, country, city, fields, levels, language, tuition_min_eur, tuition_max_eur, tuition_note, living_eur_month, app_fee_eur, app_fee_note, min_ielts, exams, requirements, deadline_note, scholarships_note, url, sort)
values
  ('Technical University of Munich (TUM)', 'Almaniya', 'Münhen', array['engineering', 'cs', 'science', 'business']::text[], array['bachelor', 'master']::text[], 'İngilis / Alman', 4000, 12000, 'Qeyri-AB tələbələr (2024/25-dən): bakalavr semestrdə 2 000–3 000 €, magistr 4 000–6 000 €. Üstəlik ~150 € semestr haqqı.', 1200, 0, 'Əksər proqramlar üçün müraciət birbaşa TUMonline-da, rüsumsuz.', 6.5, 'Bakalavr: bəzi proqramlarda qəbul testi/SAT; magistr: bəzi proqramlarda GRE.', 'Azərbaycan attestatı ilə birbaşa bakalavra qəbul adətən mümkün deyil: əvvəlcə Azərbaycanda 1–2 il universitet təhsili və ya Studienkolleg + Feststellungsprüfung lazımdır. Magistr: uyğun bakalavr dərəcəsi.', 'Proqramdan asılı; qış semestri üçün müraciətlər adətən yaz aylarında bağlanır.', 'DAAD, Deutschlandstipendium.', 'https://www.tum.de/en/studies/fees/tuition', 10),
  ('Politecnico di Milano', 'İtaliya', 'Milan', array['engineering', 'arts', 'cs']::text[], array['bachelor', 'master']::text[], 'İngilis / İtalyan', 900, 3900, 'Gəlirdən asılı: təxminən 900–3 900 €/il (qeyri-AB standart məbləğ ~3 900 €).', 1100, 150, 'Müraciət haqqı mərhələdən asılı olaraq ~50–150 €, geri qaytarılmır.', 6.0, 'Bakalavr: SAT və ya Politecnico-nun TOL/TIL testi; dizayn/memarlıq magistri üçün portfolio.', '12 illik orta təhsil; magistr üçün uyğun bakalavr dərəcəsi.', 'Bir neçə müraciət mərhələsi, adətən payızdan yaza qədər.', 'Gəlirə əsaslanan regional (DSU) təqaüdlər, Politecnico mükafatları.', 'https://www.polimi.it/en/prospective-students/how-much-does-it-cost', 20),
  ('University of Debrecen', 'Macarıstan', 'Debrecen', array['medicine', 'engineering', 'business', 'science']::text[], array['bachelor', 'master']::text[], 'İngilis', null, 15600, 'Tibb: 16 900 $/il (2026/27). Digər proqramlar daha ucuzdur.', 600, 140, '150 $ müraciət haqqı; qəbul olunduqda 350 $ giriş haqqı.', null, 'Tibb: biologiya və kimya üzrə giriş imtahanı, müsahibə.', 'Orta məktəb attestatı; tibb üçün biologiya və kimya biliyi.', 'Adətən yaz-yay aylarında, bir neçə mərhələ.', 'Stipendium Hungaricum ilə pulsuz təhsil mümkündür.', 'https://edu.unideb.hu/p/tuition-fee-application-entrance-fee', 30),
  ('Charles University', 'Çexiya', 'Praqa', array['medicine', 'social', 'science', 'humanities', 'law']::text[], array['bachelor', 'master']::text[], 'İngilis / Çex', 1000, 24000, 'İngilisdilli proqramlar ~1 000–24 000 €/il (orta ~6 000 €). Çex dilində təhsil pulsuzdur.', 900, 41, 'Fakültədən asılı: məs. Sosial Elmlər ~940 CZK (~41 €), Tibb 285 €.', null, 'Fakültənin qəbul imtahanı (sahəyə görə).', 'Attestatın/diplomun Çexiyada tanınması (nostrifikasiya) tələb oluna bilər.', 'Adətən fevral–aprel (fakültədən asılı).', 'Çex hökuməti təqaüdləri, fakültə təqaüdləri.', 'https://cuni.cz/UKEN-372.html', 40),
  ('University of Tartu', 'Estoniya', 'Tartu', array['cs', 'science', 'social', 'humanities', 'business']::text[], array['bachelor', 'master']::text[], 'İngilis', null, null, 'Proqramdan asılı. 2026/27-dən qeyri-AB tələbələr üçün ödənişsiz yerlər təklif olunmur, bəzi proqramlarda endirim var.', 700, 100, '100 € (2 proqrama qədər), DreamApply vasitəsilə.', null, 'Motivasiya məktubu, bəzi proqramlarda müsahibə.', 'Magistr üçün uyğun bakalavr dərəcəsi və ingilis dili sertifikatı.', 'Adətən yaz aylarında — proqram səhifəsində yoxla.', 'Məhdud sayda universitet təqaüdü.', 'https://ut.ee/en/content/application-fee', 50),
  ('Middle East Technical University (ODTÜ)', 'Türkiyə', 'Ankara', array['engineering', 'cs', 'science', 'arts', 'business', 'social']::text[], array['bachelor', 'master']::text[], 'İngilis', 1500, 2200, 'Təxminən 1 600–2 400 $/il (fakültədən asılı).', 500, 0, '2026/27 üçün müraciət haqqı yoxdur.', null, 'YÖS, SAT, ACT, IB və ya ABITUR.', 'Qəbul imtahanı nəticəsi + attestat. İngilis dili sertifikatı (məs. TOEFL iBT 75+) olmasa, hazırlıq ili keçirsən.', 'Bakalavr: 2026-cı ildə 1 iyun – 12 iyul.', 'Türkiye Bursları ilə də qəbul mümkündür.', 'https://iso.metu.edu.tr/en/tum-duyurular', 60),
  ('Koç University', 'Türkiyə', 'İstanbul', array['business', 'engineering', 'cs', 'law', 'medicine', 'social', 'humanities']::text[], array['bachelor', 'master']::text[], 'İngilis', 20000, 27000, 'Təxminən 21 500 $/il; tibb ~29 000 $/il.', 800, 0, 'Bakalavr üçün müraciət haqqı yoxdur.', null, 'SAT/ACT, IB, A-Level və ya ekvivalent.', 'Güclü akademik nəticələr və imtahan balı; ingilis dili sertifikatı.', 'Bir neçə müraciət mərhələsi — universitet saytında yoxla.', '25%, 50%, 75% və 100% təqaüdlər qəbul zamanı avtomatik nəzərdən keçirilir (tibb istisna).', 'https://international.ku.edu.tr/undergraduate-programs/tuition-and-scholarships/', 70),
  ('KU Leuven', 'Belçika', 'Leuven', array['engineering', 'business', 'law', 'science', 'humanities']::text[], array['bachelor', 'master']::text[], 'İngilis / Holland', 9500, 9500, 'Qeyri-AB tələbələr üçün təxminən 9 500 €/il (60 kredit); bəzi proqramlarda fərqlidir.', 1000, 90, 'Müraciət haqqı 90 €.', null, 'Bəzi proqramlarda GRE/GMAT.', 'Magistr: uyğun bakalavr dərəcəsi və ingilis dili sertifikatı.', 'Qeyri-AB namizədlər üçün adətən yazdan əvvəl — proqram səhifəsində yoxla.', 'Bəzi fakültələrdə qeyri-AB tələbələr üçün qismən təhsil haqqı güzəşti.', 'https://www.kuleuven.be/english/education/student/fees', 80),
  ('University of Warsaw', 'Polşa', 'Varşava', array['social', 'business', 'humanities', 'cs', 'law']::text[], array['bachelor', 'master']::text[], 'İngilis / Polyak', null, null, 'İngilisdilli proqramlar üçün qeyri-AB tələbələr ödəyir; məbləğ proqramdan asılıdır (Polşada ümumən ~1 000–18 000 €/il).', 800, 20, 'Qəbul (recruitment) haqqı — Polşada adətən 20–50 €.', null, 'Proqramdan asılı.', 'Attestat/diplomun tanınması; ingilis dili sertifikatı.', 'Adətən yaz-yay aylarında.', 'Polşa hökumətinin NAWA təqaüdləri.', 'https://rekrutacja.uw.edu.pl/en/application-and-tuition-fees/', 90),
  ('University of Manchester', 'Böyük Britaniya', 'Mançester', array['business', 'engineering', 'cs', 'science', 'social', 'medicine', 'law', 'humanities']::text[], array['bachelor', 'master']::text[], 'İngilis', 31000, 41000, 'Beynəlxalq tələbələr üçün təxmini 27 000–35 000 £/il (proqramdan asılı).', 1300, 40, 'Bakalavr: UCAS haqqı 34,50 £ (2027 qəbulu, 5 seçimə qədər). Magistr: birbaşa universitetə.', 6.5, 'A-Level/IB; Azərbaycan attestatı ilə adətən Foundation ili tələb olunur.', 'Bakalavr: Foundation ili və ya beynəlxalq diplom; magistr: uyğun bakalavr dərəcəsi.', 'UCAS: əksər bakalavr proqramları üçün 13 yanvar 2027.', 'Chevening (magistr), universitet təqaüdləri.', 'https://www.manchester.ac.uk/study/international/', 100)
on conflict (name) do update set
  country = excluded.country, city = excluded.city, fields = excluded.fields, levels = excluded.levels, language = excluded.language,
  tuition_min_eur = excluded.tuition_min_eur, tuition_max_eur = excluded.tuition_max_eur, tuition_note = excluded.tuition_note,
  living_eur_month = excluded.living_eur_month, app_fee_eur = excluded.app_fee_eur, app_fee_note = excluded.app_fee_note,
  min_ielts = excluded.min_ielts, exams = excluded.exams, requirements = excluded.requirements, deadline_note = excluded.deadline_note,
  scholarships_note = excluded.scholarships_note, url = excluded.url, sort = excluded.sort, updated_at = now();
