import { useLang } from '../i18n';
import { FREE_EVENT_LIMIT } from '../config';

const az = {
  demoBanner: 'Demo rejim: məlumatlar yalnız bu brauzerdə saxlanılır.',
  demoLogin: 'Demo hesabla daxil ol',
  demoAdmin: 'Admin',
  demoUser: 'İstifadəçi',
  loading: 'Yüklənir…',
  retry: 'Yenidən cəhd et',
  loadError: 'Məlumatları yükləmək alınmadı.',
  saveError: 'Yadda saxlamaq alınmadı. Yenidən cəhd et.',
  back: 'Geri',
  nav: { opportunities: 'Fürsətlər', tracker: 'Müraciətlərim', profile: 'Profil', admin: 'Admin', logout: 'Çıxış', home: 'Ana səhifə' },
  auth: {
    loginTitle: 'Xoş gəldin',
    loginSub: 'Hesabına daxil ol və fürsətləri izləməyə davam et.',
    registerTitle: 'Hesab yarat',
    registerSub: 'Pulsuzdur. Maraqlarını seç, sənə uyğun fürsətləri gör.',
    name: 'Ad Soyad',
    namePh: 'Aysel Məmmədova',
    email: 'E-poçt',
    emailPh: 'sen@example.com',
    password: 'Şifrə',
    passwordPh: 'Ən azı 6 simvol',
    login: 'Daxil ol',
    register: 'Qeydiyyatdan keç',
    noAccount: 'Hesabın yoxdur?',
    haveAccount: 'Artıq hesabın var?',
    confirmTitle: 'E-poçtunu təsdiqlə',
    confirmText: (email: string) => `${email} ünvanına təsdiq linki göndərdik. Linkə keçəndən sonra daxil ola bilərsən.`,
    errors: {
      invalid_credentials: 'E-poçt və ya şifrə yanlışdır.',
      email_taken: 'Bu e-poçtla artıq hesab var. Daxil olmağa çalış.',
      weak_password: 'Şifrə çox zəifdir — ən azı 6 simvol olsun.',
      email_not_confirmed: 'Əvvəlcə e-poçtuna gələn linklə hesabını təsdiqlə.',
      not_allowed: 'Bu əməliyyata icazən yoxdur.',
      unknown: 'Nəsə alınmadı. Bir az sonra yenidən cəhd et.',
      nameRequired: 'Adını və soyadını yaz.',
      emailInvalid: 'E-poçt ünvanı düzgün görünmür.',
      passwordShort: 'Şifrə ən azı 6 simvol olmalıdır.',
    },
  },
  list: {
    title: 'Fürsətlər',
    sub: (n: number) => `${n} açıq fürsət`,
    search: 'Ad, proqram və ya ölkə üzrə axtar…',
    forYou: 'Mənim maraqlarım',
    allPrograms: 'Bütün proqramlar',
    allKinds: 'Bütün növlər',
    allCountries: 'Bütün ölkələr',
    online: 'Onlayn',
    closingSoon: 'Son 7 gün',
    fullyFunded: 'Xərclər qarşılanır',
    showClosed: 'Bağlananları da göstər',
    clear: 'Filtrləri təmizlə',
    empty: 'Bu filtrlərə uyğun fürsət tapılmadı.',
    noInterests: 'Maraqlarını seçsən, sənə uyğun fürsətləri ayırarıq.',
    pickInterests: 'Maraqları seç',
    draft: 'Qaralama',
  },
  card: {
    save: 'Saxla',
    saved: 'Saxlanılıb',
    closed: 'Bağlanıb',
    deadline: 'Son tarix',
  },
  detail: {
    notFound: 'Fürsət tapılmadı və ya artıq mövcud deyil.',
    apply: 'Rəsmi səhifədə müraciət et',
    applyHint: 'Müraciət rəsmi mənbədə edilir. Müraciət edəndən sonra statusu burada yenilə.',
    track: 'Müraciətlərimə əlavə et',
    remove: 'Siyahıdan çıxar',
    status: 'Status',
    about: 'Haqqında',
    when: 'Tarixlər',
    where: 'Yer',
    type: 'Növ',
    costs: 'Xərclər',
    program: 'Proqram',
    organizer: 'Təşkilatçı',
    interests: 'Mövzular',
  },
  tracker: {
    title: 'Müraciətlərim',
    sub: 'Saxladığın və müraciət etdiyin fürsətlər bir yerdə.',
    all: 'Hamısı',
    empty: 'Hələ heç nə saxlamamısan.',
    emptyCta: 'Fürsətlərə bax',
    usage: (n: number) => `Pulsuz plan: ${n} / ${FREE_EVENT_LIMIT} fürsət`,
    upgrade: 'Limitsiz izləmə üçün Premium — 3 ₼ / ay',
  },
  limit: {
    title: 'Pulsuz plan limiti',
    text: `Pulsuz planda eyni anda ${FREE_EVENT_LIMIT} fürsət izləyə bilərsən. Yenisini əlavə etmək üçün birini siyahıdan çıxar və ya Premium-a keç.`,
    ok: 'Aydındır',
    manage: 'Müraciətlərimə keç',
  },
  profile: {
    title: 'Profil',
    onboardingTitle: 'Səni tanıyaq 👋',
    onboardingSub: 'Maraqlarını seç ki, sənə uyğun fürsətləri ön plana çıxaraq. Sonra dəyişə bilərsən.',
    name: 'Ad Soyad',
    email: 'E-poçt',
    country: 'Yaşadığın ölkə',
    countryPh: 'Seç…',
    interests: 'Maraq sahələri',
    interestsHint: 'Bir neçəsini seçə bilərsən',
    plan: 'Plan',
    basic: 'Pulsuz',
    premium: 'Premium',
    save: 'Yadda saxla',
    continue: 'Davam et',
    saved: 'Yadda saxlanıldı ✓',
  },
  admin: {
    title: 'Fürsətləri idarə et',
    sub: 'Əlavə et, redaktə et, dərc et və ya gizlət.',
    add: 'Yeni fürsət',
    edit: 'Redaktə',
    delete: 'Sil',
    confirmDelete: (title: string) => `“${title}” silinsin? Bu geri qaytarıla bilməz.`,
    published: 'Dərc olunub',
    draft: 'Qaralama',
    empty: 'Hələ fürsət yoxdur. İlkini əlavə et.',
    newTitle: 'Yeni fürsət',
    editTitle: 'Fürsəti redaktə et',
    f: {
      title: 'Başlıq',
      program: 'Proqram',
      otherProgram: 'Proqramın adı',
      organizer: 'Təşkilatçı',
      kind: 'Növ',
      country: 'Ölkə',
      city: 'Şəhər',
      online: 'Onlayn keçirilir',
      interests: 'Mövzular',
      deadline: 'Müraciət son tarixi',
      start: 'Başlama tarixi',
      end: 'Bitmə tarixi',
      costs: 'Xərclər',
      url: 'Rəsmi link',
      description: 'Təsvir',
      publish: 'Dərc et (istifadəçilər görsün)',
      save: 'Yadda saxla',
      cancel: 'Ləğv et',
      required: 'Bu sahə vacibdir.',
      badUrl: 'Link https:// ilə başlamalıdır.',
      badDates: 'Bitmə tarixi başlamadan əvvəl ola bilməz.',
    },
  },
  daysLeft: (d: number) => (d < 0 ? 'Bağlanıb' : d === 0 ? 'Bu gün bitir' : d === 1 ? 'Sabah bitir' : `${d} gün qaldı`),
};

type AppText = typeof az;

const en: AppText = {
  demoBanner: 'Demo mode: data is stored only in this browser.',
  demoLogin: 'Log in with a demo account',
  demoAdmin: 'Admin',
  demoUser: 'User',
  loading: 'Loading…',
  retry: 'Try again',
  loadError: 'Couldn’t load the data.',
  saveError: 'Couldn’t save. Please try again.',
  back: 'Back',
  nav: { opportunities: 'Opportunities', tracker: 'My applications', profile: 'Profile', admin: 'Admin', logout: 'Log out', home: 'Home' },
  auth: {
    loginTitle: 'Welcome back',
    loginSub: 'Log in to keep tracking your opportunities.',
    registerTitle: 'Create your account',
    registerSub: 'It’s free. Pick your interests and see matching opportunities.',
    name: 'Full name',
    namePh: 'Aysel Mammadova',
    email: 'Email',
    emailPh: 'you@example.com',
    password: 'Password',
    passwordPh: 'At least 6 characters',
    login: 'Log in',
    register: 'Sign up',
    noAccount: 'No account yet?',
    haveAccount: 'Already have an account?',
    confirmTitle: 'Confirm your email',
    confirmText: (email: string) => `We sent a confirmation link to ${email}. Open it, then log in.`,
    errors: {
      invalid_credentials: 'Wrong email or password.',
      email_taken: 'An account with this email already exists. Try logging in.',
      weak_password: 'Password is too weak — use at least 6 characters.',
      email_not_confirmed: 'Please confirm your account using the link in your email first.',
      not_allowed: 'You’re not allowed to do that.',
      unknown: 'Something went wrong. Please try again in a moment.',
      nameRequired: 'Please enter your full name.',
      emailInvalid: 'That email address doesn’t look right.',
      passwordShort: 'Password must be at least 6 characters.',
    },
  },
  list: {
    title: 'Opportunities',
    sub: (n: number) => `${n} open opportunit${n === 1 ? 'y' : 'ies'}`,
    search: 'Search by title, program or country…',
    forYou: 'My interests',
    allPrograms: 'All programs',
    allKinds: 'All types',
    allCountries: 'All countries',
    online: 'Online',
    closingSoon: 'Closing in 7 days',
    fullyFunded: 'Funded',
    showClosed: 'Show closed ones too',
    clear: 'Clear filters',
    empty: 'No opportunities match these filters.',
    noInterests: 'Pick your interests and we’ll highlight matching opportunities.',
    pickInterests: 'Pick interests',
    draft: 'Draft',
  },
  card: { save: 'Save', saved: 'Saved', closed: 'Closed', deadline: 'Deadline' },
  detail: {
    notFound: 'Opportunity not found or no longer available.',
    apply: 'Apply on the official page',
    applyHint: 'You apply at the official source. Update the status here after applying.',
    track: 'Add to my applications',
    remove: 'Remove from list',
    status: 'Status',
    about: 'About',
    when: 'Dates',
    where: 'Location',
    type: 'Type',
    costs: 'Costs',
    program: 'Program',
    organizer: 'Organizer',
    interests: 'Topics',
  },
  tracker: {
    title: 'My applications',
    sub: 'Everything you saved and applied to, in one place.',
    all: 'All',
    empty: 'You haven’t saved anything yet.',
    emptyCta: 'Browse opportunities',
    usage: (n: number) => `Free plan: ${n} / ${FREE_EVENT_LIMIT} opportunities`,
    upgrade: 'Unlimited tracking with Premium — 3 ₼ / mo',
  },
  limit: {
    title: 'Free plan limit',
    text: `On the free plan you can track ${FREE_EVENT_LIMIT} opportunities at a time. Remove one to add another, or upgrade to Premium.`,
    ok: 'Got it',
    manage: 'Go to my applications',
  },
  profile: {
    title: 'Profile',
    onboardingTitle: 'Let’s get to know you 👋',
    onboardingSub: 'Pick your interests so we can put matching opportunities first. You can change them later.',
    name: 'Full name',
    email: 'Email',
    country: 'Country you live in',
    countryPh: 'Select…',
    interests: 'Interest areas',
    interestsHint: 'Pick as many as you like',
    plan: 'Plan',
    basic: 'Free',
    premium: 'Premium',
    save: 'Save',
    continue: 'Continue',
    saved: 'Saved ✓',
  },
  admin: {
    title: 'Manage opportunities',
    sub: 'Add, edit, publish or hide.',
    add: 'New opportunity',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: (title: string) => `Delete “${title}”? This can’t be undone.`,
    published: 'Published',
    draft: 'Draft',
    empty: 'No opportunities yet. Add the first one.',
    newTitle: 'New opportunity',
    editTitle: 'Edit opportunity',
    f: {
      title: 'Title',
      program: 'Program',
      otherProgram: 'Program name',
      organizer: 'Organizer',
      kind: 'Type',
      country: 'Country',
      city: 'City',
      online: 'Takes place online',
      interests: 'Topics',
      deadline: 'Application deadline',
      start: 'Start date',
      end: 'End date',
      costs: 'Costs',
      url: 'Official link',
      description: 'Description',
      publish: 'Publish (visible to users)',
      save: 'Save',
      cancel: 'Cancel',
      required: 'This field is required.',
      badUrl: 'The link must start with https://',
      badDates: 'End date can’t be before the start date.',
    },
  },
  daysLeft: (d: number) => (d < 0 ? 'Closed' : d === 0 ? 'Closes today' : d === 1 ? 'Closes tomorrow' : `${d} days left`),
};

export const appText = { az, en };

export function useAppText() {
  const { lang } = useLang();
  return { tx: appText[lang], lang };
}
