import { useLang } from '../i18n';
import { FREE_EVENT_LIMIT } from '../config';

const az = {
  demoBanner: 'Demo rejim: məlumatlar yalnız bu brauzerdə saxlanılır.',
  demoLogin: 'Demo hesabla daxil ol',
  demoAdmin: 'Admin',
  demoUser: 'İstifadəçi',
  loading: 'Yüklənir…',
  retry: 'Yenidən cəhd et',
  loadError: 'Məlumatları yükləmək alınmadı.',
  saveError: 'Yadda saxlamaq alınmadı. Yenidən cəhd et.',
  back: 'Geri',
  nav: { opportunities: 'Fürsətlər', tracker: 'Müraciətlərim', profile: 'Profil', admin: 'Admin', users: 'İstifadəçilər', premium: 'Premium', logout: 'Çıxış', home: 'Ana səhifə' },
  auth: {
    loginTitle: 'Xoş gəldin',
    loginSub: 'Hesabına daxil ol və fürsətləri izləməyə davam et.',
    registerTitle: 'Hesab yarat',
    registerSub: 'Pulsuzdur. Maraqlarını seç, sənə uyğun fürsətləri gör.',
    name: 'Ad Soyad',
    namePh: 'Aysel Məmmədova',
    email: 'E-poçt',
    emailPh: 'sen@example.com',
    password: 'Şifrə',
    passwordPh: 'Ən azı 6 simvol',
    login: 'Daxil ol',
    register: 'Qeydiyyatdan keç',
    google: 'Google ilə davam et',
    or: 'və ya e-poçtla',
    oauthError: 'Google ilə giriş alınmadı. Yenidən cəhd et.',
    noAccount: 'Hesabın yoxdur?',
    haveAccount: 'Artıq hesabın var?',
    forgot: 'Şifrəni unutmusan?',
    forgotTitle: 'Şifrəni bərpa et',
    forgotSub: 'E-poçtunu yaz, sənə yeni şifrə təyin etmək üçün link göndərək.',
    sendLink: 'Link göndər',
    linkSentTitle: 'E-poçtuna bax',
    linkSentText: (email: string) => `${email} ünvanında hesab varsa, şifrəni yeniləmək üçün link göndərdik. Link 1 saat etibarlıdır.`,
    demoNoEmail: 'Demo rejimdə e-poçt göndərilmir. Supabase qoşulanda bu link real məktubla gələcək.',
    resetTitle: 'Yeni şifrə təyin et',
    resetSub: 'Hesabın üçün yeni şifrə yaz.',
    newPassword: 'Yeni şifrə',
    confirmPassword: 'Yeni şifrəni təkrarla',
    savePassword: 'Şifrəni yadda saxla',
    resetInvalid: 'Link etibarsızdır və ya vaxtı keçib. Yenisini istə.',
    requestNew: 'Yeni link istə',
    passwordsDiffer: 'Şifrələr eyni deyil.',
    passwordChanged: 'Şifrən yeniləndi ✓',
    backToLogin: 'Girişə qayıt',
    confirmTitle: 'E-poçtunu təsdiqlə',
    confirmText: (email: string) => `${email} ünvanına təsdiq linki göndərdik. Linkə keçəndən sonra daxil ola bilərsən.`,
    errors: {
      invalid_credentials: 'E-poçt və ya şifrə yanlışdır.',
      email_taken: 'Bu e-poçtla artıq hesab var. Daxil olmağa çalış.',
      weak_password: 'Şifrə çox zəifdir — ən azı 6 simvol olsun.',
      email_not_confirmed: 'Əvvəlcə e-poçtuna gələn linklə hesabını təsdiqlə.',
      not_allowed: 'Bu əməliyyata icazən yoxdur.',
      unknown: 'Nəsə alınmadı. Bir az sonra yenidən cəhd et.',
      nameRequired: 'Adını və soyadını yaz.',
      emailInvalid: 'E-poçt ünvanı düzgün görünmür.',
      passwordShort: 'Şifrə ən azı 6 simvol olmalıdır.',
    },
  },
  dash: {
    hello: (name: string) => (name ? `Salam, ${name} 👋` : 'Salam 👋'),
    sub: (open: number, fits: number) => (fits ? `Hazırda ${open} açıq fürsət var, ${fits}-i maraqlarına uyğundur.` : `Hazırda ${open} açıq fürsət var.`),
    saved: 'Saxlanılıb',
    applied: 'Müraciət edilib',
    accepted: 'Qəbul olunub',
    closing: 'Bu həftə bağlanır',
    upcoming: 'Yaxınlaşan son tarixlər',
    upcomingSub: 'Saxladığın, hələ müraciət etmədiyin fürsətlər',
    upcomingEmpty: 'Bəyəndiyin fürsəti saxla — son tarixi burada görünəcək və sənə xatırladacağıq.',
    allTracked: 'Hamısı',
    prep: (done: number, total: number) => `Hazırlıq ${done}/${total}`,
  },
  prep: {
    title: 'Müraciət hazırlığı',
    items: {
      cv: 'CV hazırdır',
      letter: 'Motivasiya məktubu yazılıb',
      passport: 'Pasportun müddəti yoxlanılıb',
      sending_org: 'Göndərən təşkilatla əlaqə saxlanılıb',
      form: 'Müraciət forması doldurulub',
    },
    note: 'Qeydlərim',
    notePh: 'Məs.: "Bazar ertəsi təşkilata yazdım, cavab gözləyirəm"',
    noteSaved: 'Yadda saxlanıldı ✓',
  },
  similar: {
    title: 'Oxşar fürsətlər',
  },
  list: {
    title: 'Fürsətlər',
    allTitle: 'Bütün fürsətlər',
    filters: 'Filtrlər',
    sub: (n: number) => `${n} açıq fürsət`,
    search: 'Ad, proqram və ya ölkə üzrə axtar…',
    forYou: 'Mənim maraqlarım',
    allPrograms: 'Bütün proqramlar',
    allKinds: 'Bütün növlər',
    allCountries: 'Bütün ölkələr',
    online: 'Onlayn',
    closingSoon: 'Son 7 gün',
    fullyFunded: 'Xərclər qarşılanır',
    showClosed: 'Bağlananları da göstər',
    clear: 'Filtrləri təmizlə',
    empty: 'Bu filtrlərə uyğun fürsət tapılmadı.',
    noInterests: 'Maraqlarını seçsən, sənə uyğun fürsətləri ayırarıq.',
    pickInterests: 'Maraqları seç',
    draft: 'Qaralama',
    earlyTeaser: (n: number) => `Premium istifadəçilər ${n} yeni fürsəti artıq görür. Sən ${n === 1 ? 'onu' : 'onları'} 24 saat sonra görəcəksən.`,
    seePremium: 'Premium-a bax',
    premiumFilter: 'Bu filtr Premium-dadır',
    newBadge: 'Yeni',
    sortBest: 'Ən uyğun',
    sortDeadline: 'Son tarix',
    match: (n: number) => `${n}% uyğun`,
    matchReasons: { interests: 'maraqlarına uyğun', funded: 'xərclər qarşılanır', partlyFunded: 'xərclər qismən qarşılanır', online: 'onlayn', country: 'sənin ölkəndə' },
    forYouTitle: (n: number) => (n === 1 ? 'Sənə uyğun 1 yeni imkan var' : `Sənə uyğun ${n} yeni imkan var`),
    forYouSoon: (d: number) => (d <= 0 ? 'biri bu gün bağlanır' : d === 1 ? 'biri sabah bağlanır' : `birinin son tarixi ${d} gündür`),
  },
  card: {
    save: 'Saxla',
    saved: 'Saxlanılıb',
    closed: 'Bağlanıb',
    deadline: 'Son tarix',
  },
  detail: {
    notFound: 'Fürsət tapılmadı və ya artıq mövcud deyil.',
    apply: 'Rəsmi səhifədə müraciət et',
    applyHint: 'Müraciət rəsmi mənbədə edilir. Müraciət edəndən sonra statusu burada yenilə.',
    track: 'Müraciətlərimə əlavə et',
    remove: 'Siyahıdan çıxar',
    status: 'Status',
    about: 'Haqqında',
    when: 'Tarixlər',
    where: 'Yer',
    type: 'Növ',
    costs: 'Xərclər',
    program: 'Proqram',
    organizer: 'Təşkilatçı',
    interests: 'Mövzular',
    sendingOrg: 'Azərbaycandan göndərən təşkilat',
    sendingOrgHint: 'Bu proqrama birbaşa yox, bu təşkilat vasitəsilə müraciət olunur. Əlaqə saxla:',
  },
  tracker: {
    title: 'Müraciətlərim',
    sub: 'Saxladığın və müraciət etdiyin fürsətlər bir yerdə.',
    all: 'Hamısı',
    empty: 'Hələ heç nə saxlamamısan.',
    emptyCta: 'Fürsətlərə bax',
    usage: (n: number) => `Pulsuz plan: ${n} / ${FREE_EVENT_LIMIT} fürsət`,
    upgrade: 'Limitsiz izləmə üçün Premium — 3 ₼ / ay',
  },
  limit: {
    title: 'Pulsuz plan limiti',
    text: `Pulsuz planda eyni anda ${FREE_EVENT_LIMIT} fürsət izləyə bilərsən. Yenisini əlavə etmək üçün birini siyahıdan çıxar və ya Premium-a keç.`,
    ok: 'Aydındır',
    manage: 'Müraciətlərimə keç',
  },
  profile: {
    title: 'Profil',
    onboardingTitle: 'Səni tanıyaq 👋',
    onboardingSub: 'Maraqlarını seç ki, sənə uyğun fürsətləri ön plana çıxaraq. Sonra dəyişə bilərsən.',
    name: 'Ad Soyad',
    email: 'E-poçt',
    country: 'Yaşadığın ölkə',
    countryPh: 'Seç…',
    interests: 'Maraq sahələri',
    interestsHint: 'Bir neçəsini seçə bilərsən',
    plan: 'Plan',
    basic: 'Pulsuz',
    premium: 'Premium',
    save: 'Yadda saxla',
    continue: 'Davam et',
    saved: 'Yadda saxlanıldı ✓',
    about: 'Haqqımda',
    aboutHint: 'Təhsil, təcrübə, bacarıqlar, könüllülük keçmişi. AI köməkçisi məktub hazırlayanda bundan istifadə edir.',
    aboutPh: 'Məs.: ADA Universiteti, 3-cü kurs, beynəlxalq münasibətlər. 2 il "Gənclər Evi"ndə könüllü, ekologiya kampaniyaları təşkil etmişəm. İngilis dili B2.',
    photo: 'Profil şəkli',
    changePhoto: 'Şəkli dəyiş',
    removePhoto: 'Sil',
    photoHint: 'JPG, PNG və ya WEBP. Kvadrat kəsilir.',
    photoError: 'Şəkil yüklənmədi. Başqa şəkil seç (JPG, PNG, WEBP).',
    headline: 'Qısa təqdimat',
    headlinePh: 'Məs.: Tələbə · ADA Universiteti · Ekologiya könüllüsü',
    tabProfile: 'Profil',
    tabPremium: 'Plan',
    tabSettings: 'Parametrlər',
    security: 'Şifrəni dəyiş',
    securityHint: 'Google ilə daxil olursansa, burada e-poçtla giriş üçün şifrə də təyin edə bilərsən.',
    notifications: 'E-poçt bildirişləri',
    digest: 'Yeni fürsətlər haqqında xülasə',
    digestFree: 'Həftədə 1 dəfə (bazar ertəsi) — maraqlarına uyğun yeni fürsətlər.',
    digestPremium: 'Hər gün — maraqlarına uyğun yeni fürsətlər.',
    reminders: 'Son tarix xatırlatmaları',
    remindersPremium: 'Saxladığın fürsətin son tarixinə 7, 3 və 1 gün qalanda.',
    remindersFree: 'Yalnız Premium-da. Premium — 3 ₼ / ay.',
  },
  guest: {
    listBanner: 'Pulsuz qeydiyyatdan keç: fürsətləri saxla, müraciətlərini izlə, sənə uyğun olanları gör.',
    signUp: 'Qeydiyyat',
    logIn: 'Daxil ol',
    sidebar: 'Fürsətləri saxlamaq və müraciətləri izləmək üçün pulsuz hesab yarat.',
    aiText: 'AI müraciət köməkçisi hesabı olan Premium istifadəçilər üçündür. Əvvəlcə pulsuz qeydiyyatdan keç.',
  },
  share: {
    title: 'Paylaş',
    copy: 'Linki kopyala',
    copied: 'Kopyalandı ✓',
    calendar: 'Son tarixi təqvimə əlavə et',
    google: 'Google Təqvim',
    ics: 'Apple / Outlook (.ics)',
    eventTitle: (title: string) => `Son tarix: ${title}`,
    text: (title: string, date: string) => `${title} — son tarix ${date}`,
  },
  applied: {
    question: 'Müraciət etdin?',
    text: 'Etdinsə, statusu "Müraciət edilib" edək ki, izləmək rahat olsun.',
    yes: 'Bəli, müraciət etdim',
    no: 'Hələ yox',
  },
  peers: {
    title: 'Qəbul olunan digər iştirakçılar',
    sub: 'Eyni proqrama qəbul olunanlarla tanış ol: yol, viza və yaşayış üçün birlikdə planlaşdırın.',
    share: 'Adımı və e-poçtumu bu proqrama qəbul olunan digərləri ilə paylaş',
    none: 'Hələ ki əlaqəsini paylaşan başqa iştirakçı yoxdur. Kimsə qoşulan kimi burada görünəcək.',
  },
  ai: {
    title: 'AI müraciət köməkçisi',
    sub: 'Motivasiya məktubunu öz hekayənlə hazırla və göndərməzdən əvvəl yoxlat.',
    open: 'AI köməkçini aç',
    locked: 'AI köməkçi Premium-dadır: motivasiya məktubu köməkçisi və müraciət yoxlanışı.',
    tabLetter: 'Motivasiya məktubu',
    tabReview: 'Müraciəti yoxlat',
    comingSoon: 'AI köməkçi tezliklə aktiv olacaq. Hər şey hazırdır — işə düşən kimi burada istifadə edə biləcəksən.',
    letterIntro: 'AI hazır məktub yazmır. Əvvəlcə sənə bu elana uyğun suallar verir, sonra yalnız sənin cavablarından məktubun skeletini qurur. Son sözü sən yazırsan.',
    start: 'Sualları hazırla',
    thinking: 'AI düşünür…',
    answerPh: 'Konkret yaz: nə etdin, harada, nə öyrəndin…',
    letterLang: 'Məktubun dili',
    makeDraft: 'Qaralama hazırla',
    needAnswers: 'Ən azı bir suala cavab yaz.',
    draftTitle: 'Qaralama',
    draftNote: 'Bu, başlanğıc nöqtəsidir. [Kvadrat mötərizədəki] yerləri doldur və məktubu öz səsinlə yenidən yaz — komissiyalar şablon məktubları tez tanıyır.',
    copy: 'Kopyala',
    copied: 'Kopyalandı ✓',
    tips: 'Göndərməzdən əvvəl',
    missing: 'Əlavə etməli olduğun məlumat',
    again: 'AI ilə yenidən başla',
    writeMyself: 'Özüm yazacam',
    myLetter: 'Motivasiya məktubum',
    letterPh: 'Məktubunu bura yaz və ya yapışdır…',
    saveLetter: 'Yadda saxla',
    unsaved: 'Yadda saxlanmamış dəyişikliklər var',
    savedAt: (when: string) => `Yadda saxlanılıb · ${when}`,
    reviewIntro: 'Məktubunu və ya CV-ni fayl kimi yüklə, ya da mətnini yapışdır. AI onu bu elanın tələbləri ilə müqayisə edib konkret rəy verəcək.',
    docType: 'Sənəd',
    docLetter: 'Motivasiya məktubu',
    docCv: 'CV',
    reviewPh: 'Mətni bura yapışdır (ən azı 50 simvol)…',
    upload: 'Fayl yüklə',
    uploadHint: 'PDF, DOCX və ya TXT, 3 MB-a qədər. Ya da mətni aşağıya yapışdır.',
    fromFile: (name: string) => `Mətn "${name}" faylından götürüldü — göndərməzdən əvvəl düzəldə bilərsən.`,
    pdfAttached: 'PDF olduğu kimi yoxlanacaq (dizayn və skan edilmiş səhifələr daxil).',
    removeFile: 'Faylı çıxar',
    fileType: 'Bu fayl növü dəstəklənmir. PDF, DOCX və ya TXT seç (köhnə .doc-u Word-də .docx kimi saxla).',
    fileTooBig: 'Fayl çox böyükdür (maksimum 3 MB).',
    fileRead: 'Faylı oxumaq alınmadı. Başqa fayl seç və ya mətni yapışdır.',
    reviewBtn: 'Yoxla',
    tooShort: 'Mətn çox qısadır (ən azı 50 simvol).',
    score: 'Uyğunluq balı',
    strengths: 'Güclü tərəflər',
    issues: 'Düzəltməli olduğun yerlər',
    suggestion: 'Təklif',
    missingTitle: 'Komissiya bunu axtaracaq',
    remaining: (n: number) => `Bu gün ${n} AI sorğusu qalıb`,
    errors: {
      premium_required: 'AI köməkçi yalnız Premium istifadəçilər üçündür.',
      daily_limit: 'Bu günkü AI limitinə çatdın. Sabah yenidən cəhd et.',
      refused: 'AI bu sorğunu emal edə bilmədi. Mətni dəyişib yenidən cəhd et.',
      ai_unavailable: 'AI köməkçi hazırda əlçatan deyil. Bir az sonra yenidən cəhd et.',
      not_configured: 'AI köməkçi tezliklə aktiv olacaq.',
      unknown: 'Nəsə alınmadı. Yenidən cəhd et.',
    },
  },
  premium: {
    title: 'Premium',
    sub: 'Heç bir fürsəti qaçırmamaq istəyənlər üçün.',
    current: 'Sənin planın',
    active: 'Premium aktivdir ✦',
    free: 'Pulsuz',
    price: '3 ₼ / ay',
    feature: 'Xüsusiyyət',
    rows: [
      { name: 'Fürsətlər siyahısı, axtarış, maraq və ölkə filtrləri', free: true, premium: true },
      { name: 'Eyni anda izlənən fürsətlər', free: '3', premium: 'Limitsiz' },
      { name: 'Yeni fürsətlər haqqında e-poçt xülasəsi', free: 'Həftəlik', premium: 'Gündəlik' },
      { name: 'Yeni fürsətlərə erkən giriş (24 saat əvvəl)', free: false, premium: true },
      { name: 'Təkmil filtrlər: xərclər qarşılanır, son 7 gün', free: false, premium: true },
      { name: 'Son tarix xatırlatmaları (7, 3, 1 gün əvvəl)', free: false, premium: true },
      { name: 'Ağıllı uyğunlaşdırma: hər fürsət üçün uyğunluq faizi', free: false, premium: true },
      { name: 'AI motivasiya məktubu köməkçisi', free: false, premium: true },
      { name: 'AI müraciət yoxlanışı (bal və konkret rəy)', free: false, premium: true },
    ],
    cta: 'Onlayn ödəniş tezliklə',
    ctaNote: 'Premium-u hazırda komanda aktivləşdirir. Onlayn ödəniş tezliklə əlavə olunacaq.',
    activeSub: 'Bütün Premium imkanları açıqdır: limitsiz izləmə, erkən giriş, xatırlatmalar, ağıllı uyğunlaşdırma və AI köməkçi.',
    cancelTitle: 'Premium-u ləğv et',
    cancelSub: 'Pulsuz plana keçəcəksən. Saxladığın fürsətlər qalır, amma yenilərini yalnız 3-ə qədər izləyə biləcəksən.',
    cancelBtn: 'Premium-u ləğv et',
    cancelConfirm: 'Premium ləğv edilsin? AI köməkçi, xatırlatmalar və limitsiz izləmə bağlanacaq.',
    cancelled: 'Premium ləğv edildi. İndi pulsuz plandasan.',
  },
  users: {
    title: 'İstifadəçilər',
    sub: (n: number, p: number) => `${n} istifadəçi · ${p} Premium`,
    search: 'Ad və ya e-poçt üzrə axtar…',
    joined: 'Qoşulub',
    makePremium: 'Premium et',
    makeBasic: 'Pulsuza qaytar',
    confirmPremium: (email: string) => `${email} Premium edilsin?`,
    confirmBasic: (email: string) => `${email} pulsuz plana qaytarılsın?`,
    admin: 'Admin',
    empty: 'İstifadəçi tapılmadı.',
  },
  admin: {
    title: 'Fürsətləri idarə et',
    sub: 'Əlavə et, redaktə et, dərc et və ya gizlət.',
    add: 'Yeni fürsət',
    edit: 'Redaktə',
    delete: 'Sil',
    confirmDelete: (title: string) => `“${title}” silinsin? Bu geri qaytarıla bilməz.`,
    published: 'Dərc olunub',
    draft: 'Qaralama',
    empty: 'Hələ fürsət yoxdur. İlkini əlavə et.',
    newTitle: 'Yeni fürsət',
    editTitle: 'Fürsəti redaktə et',
    f: {
      title: 'Başlıq',
      program: 'Proqram',
      otherProgram: 'Proqramın adı',
      organizer: 'Təşkilatçı',
      sendingOrg: 'Göndərən təşkilat (AZ)',
      sendingOrgHint: 'Gənclər mübadilələri üçün: müraciət bu təşkilat vasitəsilə olunur.',
      sendingOrgContact: 'Göndərən təşkilatın əlaqəsi (e-poçt, telefon və ya sayt)',
      kind: 'Növ',
      country: 'Ölkə',
      city: 'Şəhər',
      online: 'Onlayn keçirilir',
      interests: 'Mövzular',
      deadline: 'Müraciət son tarixi',
      start: 'Başlama tarixi',
      end: 'Bitmə tarixi',
      costs: 'Xərclər',
      url: 'Rəsmi link',
      description: 'Təsvir',
      publish: 'Dərc et (istifadəçilər görsün)',
      save: 'Yadda saxla',
      cancel: 'Ləğv et',
      required: 'Bu sahə vacibdir.',
      badUrl: 'Link https:// ilə başlamalıdır.',
      badDates: 'Bitmə tarixi başlamadan əvvəl ola bilməz.',
    },
  },
  daysLeft: (d: number) => (d < 0 ? 'Bağlanıb' : d === 0 ? 'Bu gün bitir' : d === 1 ? 'Sabah bitir' : `${d} gün qaldı`),
};

type AppText = typeof az;

const en: AppText = {
  demoBanner: 'Demo mode: data is stored only in this browser.',
  demoLogin: 'Log in with a demo account',
  demoAdmin: 'Admin',
  demoUser: 'User',
  loading: 'Loading…',
  retry: 'Try again',
  loadError: 'Couldn’t load the data.',
  saveError: 'Couldn’t save. Please try again.',
  back: 'Back',
  nav: { opportunities: 'Opportunities', tracker: 'My applications', profile: 'Profile', admin: 'Admin', users: 'Users', premium: 'Premium', logout: 'Log out', home: 'Home' },
  auth: {
    loginTitle: 'Welcome back',
    loginSub: 'Log in to keep tracking your opportunities.',
    registerTitle: 'Create your account',
    registerSub: 'It’s free. Pick your interests and see matching opportunities.',
    name: 'Full name',
    namePh: 'Aysel Mammadova',
    email: 'Email',
    emailPh: 'you@example.com',
    password: 'Password',
    passwordPh: 'At least 6 characters',
    login: 'Log in',
    register: 'Sign up',
    google: 'Continue with Google',
    or: 'or with email',
    oauthError: 'Google sign-in didn’t work. Please try again.',
    noAccount: 'No account yet?',
    haveAccount: 'Already have an account?',
    forgot: 'Forgot your password?',
    forgotTitle: 'Reset your password',
    forgotSub: 'Enter your email and we’ll send you a link to set a new password.',
    sendLink: 'Send link',
    linkSentTitle: 'Check your email',
    linkSentText: (email: string) => `If an account exists for ${email}, we sent a link to reset your password. It’s valid for 1 hour.`,
    demoNoEmail: 'Demo mode doesn’t send emails. Once Supabase is connected this link arrives by email.',
    resetTitle: 'Set a new password',
    resetSub: 'Choose a new password for your account.',
    newPassword: 'New password',
    confirmPassword: 'Repeat new password',
    savePassword: 'Save password',
    resetInvalid: 'This link is invalid or has expired. Request a new one.',
    requestNew: 'Request a new link',
    passwordsDiffer: 'Passwords don’t match.',
    passwordChanged: 'Password updated ✓',
    backToLogin: 'Back to log in',
    confirmTitle: 'Confirm your email',
    confirmText: (email: string) => `We sent a confirmation link to ${email}. Open it, then log in.`,
    errors: {
      invalid_credentials: 'Wrong email or password.',
      email_taken: 'An account with this email already exists. Try logging in.',
      weak_password: 'Password is too weak — use at least 6 characters.',
      email_not_confirmed: 'Please confirm your account using the link in your email first.',
      not_allowed: 'You’re not allowed to do that.',
      unknown: 'Something went wrong. Please try again in a moment.',
      nameRequired: 'Please enter your full name.',
      emailInvalid: 'That email address doesn’t look right.',
      passwordShort: 'Password must be at least 6 characters.',
    },
  },
  dash: {
    hello: (name: string) => (name ? `Hi, ${name} 👋` : 'Hi 👋'),
    sub: (open: number, fits: number) => (fits ? `${open} opportunities are open right now; ${fits} match your interests.` : `${open} opportunities are open right now.`),
    saved: 'Saved',
    applied: 'Applied',
    accepted: 'Accepted',
    closing: 'Closing this week',
    upcoming: 'Upcoming deadlines',
    upcomingSub: 'Saved opportunities you haven’t applied to yet',
    upcomingEmpty: 'Save an opportunity you like — its deadline will show up here and we’ll remind you.',
    allTracked: 'See all',
    prep: (done: number, total: number) => `Prep ${done}/${total}`,
  },
  prep: {
    title: 'Application prep',
    items: {
      cv: 'CV is ready',
      letter: 'Motivation letter written',
      passport: 'Passport validity checked',
      sending_org: 'Contacted the sending organisation',
      form: 'Application form filled in',
    },
    note: 'My notes',
    notePh: 'E.g. "Emailed the organisation on Monday, waiting for a reply"',
    noteSaved: 'Saved ✓',
  },
  similar: {
    title: 'Similar opportunities',
  },
  list: {
    title: 'Opportunities',
    allTitle: 'All opportunities',
    filters: 'Filters',
    sub: (n: number) => `${n} open opportunit${n === 1 ? 'y' : 'ies'}`,
    search: 'Search by title, program or country…',
    forYou: 'My interests',
    allPrograms: 'All programs',
    allKinds: 'All types',
    allCountries: 'All countries',
    online: 'Online',
    closingSoon: 'Closing in 7 days',
    fullyFunded: 'Funded',
    showClosed: 'Show closed ones too',
    clear: 'Clear filters',
    empty: 'No opportunities match these filters.',
    noInterests: 'Pick your interests and we’ll highlight matching opportunities.',
    pickInterests: 'Pick interests',
    draft: 'Draft',
    earlyTeaser: (n: number) => `Premium users already see ${n} new opportunit${n === 1 ? 'y' : 'ies'}. You’ll see ${n === 1 ? 'it' : 'them'} in 24 hours.`,
    seePremium: 'See Premium',
    premiumFilter: 'This filter is Premium',
    newBadge: 'New',
    sortBest: 'Best match',
    sortDeadline: 'Deadline',
    match: (n: number) => `${n}% match`,
    matchReasons: { interests: 'matches your interests', funded: 'fully funded', partlyFunded: 'partly funded', online: 'online', country: 'in your country' },
    forYouTitle: (n: number) => (n === 1 ? '1 new opportunity for you' : `${n} new opportunities for you`),
    forYouSoon: (d: number) => (d <= 0 ? 'one closes today' : d === 1 ? 'one closes tomorrow' : `one closes in ${d} days`),
  },
  card: { save: 'Save', saved: 'Saved', closed: 'Closed', deadline: 'Deadline' },
  detail: {
    notFound: 'Opportunity not found or no longer available.',
    apply: 'Apply on the official page',
    applyHint: 'You apply at the official source. Update the status here after applying.',
    track: 'Add to my applications',
    remove: 'Remove from list',
    status: 'Status',
    about: 'About',
    when: 'Dates',
    where: 'Location',
    type: 'Type',
    costs: 'Costs',
    program: 'Program',
    organizer: 'Organizer',
    interests: 'Topics',
    sendingOrg: 'Sending organisation in Azerbaijan',
    sendingOrgHint: 'You apply through this organisation, not directly. Contact:',
  },
  tracker: {
    title: 'My applications',
    sub: 'Everything you saved and applied to, in one place.',
    all: 'All',
    empty: 'You haven’t saved anything yet.',
    emptyCta: 'Browse opportunities',
    usage: (n: number) => `Free plan: ${n} / ${FREE_EVENT_LIMIT} opportunities`,
    upgrade: 'Unlimited tracking with Premium — 3 ₼ / mo',
  },
  limit: {
    title: 'Free plan limit',
    text: `On the free plan you can track ${FREE_EVENT_LIMIT} opportunities at a time. Remove one to add another, or upgrade to Premium.`,
    ok: 'Got it',
    manage: 'Go to my applications',
  },
  profile: {
    title: 'Profile',
    onboardingTitle: 'Let’s get to know you 👋',
    onboardingSub: 'Pick your interests so we can put matching opportunities first. You can change them later.',
    name: 'Full name',
    email: 'Email',
    country: 'Country you live in',
    countryPh: 'Select…',
    interests: 'Interest areas',
    interestsHint: 'Pick as many as you like',
    plan: 'Plan',
    basic: 'Free',
    premium: 'Premium',
    save: 'Save',
    continue: 'Continue',
    saved: 'Saved ✓',
    about: 'About me',
    aboutHint: 'Education, experience, skills, volunteering background. The AI assistant uses this when drafting letters.',
    aboutPh: 'E.g.: ADA University, 3rd year, international relations. 2 years volunteering at a youth centre, organised environmental campaigns. English B2.',
    photo: 'Profile photo',
    changePhoto: 'Change photo',
    removePhoto: 'Remove',
    photoHint: 'JPG, PNG or WEBP. Cropped to a square.',
    photoError: 'Couldn’t upload the photo. Try another one (JPG, PNG, WEBP).',
    headline: 'Headline',
    headlinePh: 'E.g. Student · ADA University · Environmental volunteer',
    tabProfile: 'Profile',
    tabPremium: 'Plan',
    tabSettings: 'Settings',
    security: 'Change password',
    securityHint: 'If you sign in with Google, you can also set a password here for email sign-in.',
    notifications: 'Email notifications',
    digest: 'New opportunities digest',
    digestFree: 'Once a week (Monday) — new opportunities matching your interests.',
    digestPremium: 'Every day — new opportunities matching your interests.',
    reminders: 'Deadline reminders',
    remindersPremium: 'When a saved opportunity closes in 7, 3 and 1 days.',
    remindersFree: 'Premium only. Premium — 3 ₼ / mo.',
  },
  guest: {
    listBanner: 'Sign up for free: save opportunities, track your applications, see what fits you.',
    signUp: 'Sign up',
    logIn: 'Log in',
    sidebar: 'Create a free account to save opportunities and track your applications.',
    aiText: 'The AI application assistant is for Premium users with an account. Sign up for free first.',
  },
  share: {
    title: 'Share',
    copy: 'Copy link',
    copied: 'Copied ✓',
    calendar: 'Add the deadline to your calendar',
    google: 'Google Calendar',
    ics: 'Apple / Outlook (.ics)',
    eventTitle: (title: string) => `Deadline: ${title}`,
    text: (title: string, date: string) => `${title} — deadline ${date}`,
  },
  applied: {
    question: 'Did you apply?',
    text: 'If so, let’s mark it as "Applied" so it’s easy to track.',
    yes: 'Yes, I applied',
    no: 'Not yet',
  },
  peers: {
    title: 'Other accepted participants',
    sub: 'Meet the others accepted to the same programme: plan travel, visas and accommodation together.',
    share: 'Share my name and email with others accepted to this programme',
    none: 'Nobody else has shared their contact yet. They’ll show up here as soon as they do.',
  },
  ai: {
    title: 'AI application assistant',
    sub: 'Build your motivation letter from your own story and check it before you send.',
    open: 'Open AI assistant',
    locked: 'The AI assistant is Premium: motivation letter helper and application review.',
    tabLetter: 'Motivation letter',
    tabReview: 'Review my application',
    comingSoon: 'The AI assistant is launching soon. Everything is in place — you’ll be able to use it right here.',
    letterIntro: 'The AI doesn’t write a ready-made letter. It first asks you questions tailored to this opportunity, then builds a letter outline only from your answers. You write the final words.',
    start: 'Get my questions',
    thinking: 'The AI is thinking…',
    answerPh: 'Be concrete: what you did, where, what you learned…',
    letterLang: 'Letter language',
    makeDraft: 'Build a draft',
    needAnswers: 'Answer at least one question.',
    draftTitle: 'Draft',
    draftNote: 'This is a starting point. Fill in the [bracketed] parts and rewrite it in your own voice — committees spot template letters fast.',
    copy: 'Copy',
    copied: 'Copied ✓',
    tips: 'Before you send',
    missing: 'Information to add',
    again: 'Start over with AI',
    writeMyself: 'I’ll write it myself',
    myLetter: 'My motivation letter',
    letterPh: 'Write or paste your letter here…',
    saveLetter: 'Save',
    unsaved: 'You have unsaved changes',
    savedAt: (when: string) => `Saved · ${when}`,
    reviewIntro: 'Upload your letter or CV as a file, or paste its text. The AI compares it with this opportunity’s requirements and gives concrete feedback.',
    docType: 'Document',
    docLetter: 'Motivation letter',
    docCv: 'CV',
    reviewPh: 'Paste the text here (at least 50 characters)…',
    upload: 'Upload a file',
    uploadHint: 'PDF, DOCX or TXT, up to 3 MB. Or paste the text below.',
    fromFile: (name: string) => `Text taken from "${name}" — you can edit it before sending.`,
    pdfAttached: 'The PDF is reviewed as-is (layout and scanned pages included).',
    removeFile: 'Remove file',
    fileType: 'This file type isn’t supported. Choose PDF, DOCX or TXT (save an old .doc as .docx in Word).',
    fileTooBig: 'The file is too large (max 3 MB).',
    fileRead: 'Couldn’t read the file. Choose another one or paste the text.',
    reviewBtn: 'Review',
    tooShort: 'The text is too short (at least 50 characters).',
    score: 'Fit score',
    strengths: 'Strengths',
    issues: 'What to fix',
    suggestion: 'Suggestion',
    missingTitle: 'The committee will look for this',
    remaining: (n: number) => `${n} AI requests left today`,
    errors: {
      premium_required: 'The AI assistant is for Premium users only.',
      daily_limit: 'You’ve reached today’s AI limit. Try again tomorrow.',
      refused: 'The AI couldn’t process this request. Change the text and try again.',
      ai_unavailable: 'The AI assistant isn’t available right now. Try again in a bit.',
      not_configured: 'The AI assistant is launching soon.',
      unknown: 'Something went wrong. Please try again.',
    },
  },
  premium: {
    title: 'Premium',
    sub: 'For people who don’t want to miss a single opportunity.',
    current: 'Your plan',
    active: 'Premium is active ✦',
    free: 'Free',
    price: '3 ₼ / mo',
    feature: 'Feature',
    rows: [
      { name: 'Opportunity list, search, interest and country filters', free: true, premium: true },
      { name: 'Opportunities tracked at a time', free: '3', premium: 'Unlimited' },
      { name: 'New-opportunity email digest', free: 'Weekly', premium: 'Daily' },
      { name: 'Early access to new opportunities (24 hours earlier)', free: false, premium: true },
      { name: 'Advanced filters: funded, closing in 7 days', free: false, premium: true },
      { name: 'Deadline reminders (7, 3, 1 days before)', free: false, premium: true },
      { name: 'Smart matching: a fit score for every opportunity', free: false, premium: true },
      { name: 'AI motivation letter assistant', free: false, premium: true },
      { name: 'AI application review (score and concrete feedback)', free: false, premium: true },
    ],
    cta: 'Online payment coming soon',
    ctaNote: 'For now Premium is activated by the team. Online payment is coming soon.',
    activeSub: 'All Premium features are on: unlimited tracking, early access, reminders, smart matching and the AI assistant.',
    cancelTitle: 'Cancel Premium',
    cancelSub: 'You’ll move to the free plan. Your saved opportunities stay, but you can only track up to 3 new ones.',
    cancelBtn: 'Cancel Premium',
    cancelConfirm: 'Cancel Premium? The AI assistant, reminders and unlimited tracking will be switched off.',
    cancelled: 'Premium cancelled. You’re on the free plan now.',
  },
  users: {
    title: 'Users',
    sub: (n: number, p: number) => `${n} users · ${p} Premium`,
    search: 'Search by name or email…',
    joined: 'Joined',
    makePremium: 'Make Premium',
    makeBasic: 'Back to Free',
    confirmPremium: (email: string) => `Make ${email} Premium?`,
    confirmBasic: (email: string) => `Move ${email} back to the free plan?`,
    admin: 'Admin',
    empty: 'No users found.',
  },
  admin: {
    title: 'Manage opportunities',
    sub: 'Add, edit, publish or hide.',
    add: 'New opportunity',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: (title: string) => `Delete “${title}”? This can’t be undone.`,
    published: 'Published',
    draft: 'Draft',
    empty: 'No opportunities yet. Add the first one.',
    newTitle: 'New opportunity',
    editTitle: 'Edit opportunity',
    f: {
      title: 'Title',
      program: 'Program',
      otherProgram: 'Program name',
      organizer: 'Organizer',
      sendingOrg: 'Sending organisation (AZ)',
      sendingOrgHint: 'For youth exchanges: applications go through this organisation.',
      sendingOrgContact: 'Sending organisation contact (email, phone or website)',
      kind: 'Type',
      country: 'Country',
      city: 'City',
      online: 'Takes place online',
      interests: 'Topics',
      deadline: 'Application deadline',
      start: 'Start date',
      end: 'End date',
      costs: 'Costs',
      url: 'Official link',
      description: 'Description',
      publish: 'Publish (visible to users)',
      save: 'Save',
      cancel: 'Cancel',
      required: 'This field is required.',
      badUrl: 'The link must start with https://',
      badDates: 'End date can’t be before the start date.',
    },
  },
  daysLeft: (d: number) => (d < 0 ? 'Closed' : d === 0 ? 'Closes today' : d === 1 ? 'Closes tomorrow' : `${d} days left`),
};

export const appText = { az, en };

export function useAppText() {
  const { lang } = useLang();
  return { tx: appText[lang], lang };
}
