import { useLang } from '../i18n';
import { FREE_EVENT_LIMIT } from '../config';

const az = {
  demoBanner: 'Demo rejim: məlumatlar yalnız bu brauzerdə saxlanılır.',
  demoLogin: 'Demo hesabla daxil ol',
  demoAdmin: 'Admin',
  demoUser: 'İstifadəçi',
  demoStudent: 'Tələbə',
  loading: 'Yüklənir…',
  retry: 'Yenidən cəhd et',
  loadError: 'Məlumatları yükləmək alınmadı.',
  close: 'Bağla',
  saveError: 'Yadda saxlamaq alınmadı. Yenidən cəhd et.',
  back: 'Geri',
  navGroups: { explore: 'Kəşf et', mine: 'Mənim' },
  learn: {
    title: 'Bələdçilər',
    sub: 'Proqramlar necə işləyir, necə müraciət edilir, səfərə necə hazırlaşmalı — qısa və sadə.',
    programsTitle: 'Proqramlar',
    guidesTitle: 'Addım-addım bələdçilər',
    minutes: (n: number) => `${n} dəq oxu`,
    sources: 'Rəsmi mənbələr',
    related: 'Digər bələdçilər',
    browse: 'Uyğun fürsətlərə bax',
    allGuides: 'Bütün bələdçilər',
    useful: 'Faydalı oxu',
  },
  program: {
    about: 'Bu nədir?',
    who: 'Kimlər üçün',
    costs: 'Xərclər',
    open: (n: number) => `${n} açıq fürsət`,
    none: 'Hazırda bu proqramda açıq fürsət yoxdur. Yeni fürsətlər əlavə olunanda həftəlik xülasədə görəcəksən.',
    official: 'Rəsmi sayt',
    more: 'Proqram haqqında',
  },
  calendar: {
    title: 'Son tarixlər təqvimi',
    sub: 'Bütün fürsətlərin müraciət son tarixləri bir baxışda.',
    today: 'Bu gün',
    prev: 'Əvvəlki ay',
    next: 'Növbəti ay',
    onlyMine: 'Yalnız saxladıqlarım',
    empty: 'Bu ay son tarixi olan fürsət yoxdur.',
    more: (n: number) => `+${n} daha`,
    nextDeadline: (d: number, month: string) => `Növbəti son tarix: ${d} ${month.toLocaleLowerCase('az')}`,
    weekdays: ['B.e', 'Ç.a', 'Ç', 'C.a', 'C', 'Ş', 'B'],
    months: ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'İyun', 'İyul', 'Avqust', 'Sentyabr', 'Oktyabr', 'Noyabr', 'Dekabr'],
  },
  nav: { student: 'Tələbə', calendar: 'Təqvim', guides: 'Bələdçilər', opportunities: 'Fürsətlər', tracker: 'Müraciətlərim', profile: 'Profil', admin: 'Admin', users: 'İstifadəçilər', premium: 'Premium', logout: 'Çıxış', home: 'Ana səhifə', ai: 'AI köməkçi', map: 'Xəritə' },
  auth: {
    loginTitle: 'Xoş gəldin',
    loginSub: 'Hesabına daxil ol və fürsətləri izləməyə davam et.',
    registerTitle: 'Hesab yarat',
    registerSub: 'Pulsuzdur. Maraqlarını seç, sənə uyğun fürsətləri gör.',
    accountType: 'Hesab növü',
    typeRegular: 'Adi hesab',
    typeStudent: 'Tələbə hesabı',
    studentLoginSub: 'Tələbə hesabına daxil ol: təqaüdlər, universitetlər və təhsil yol xəritən.',
    studentRegisterSub: 'Xaricdə təhsil üçün ayrıca hesab: təqaüdlər, universitetlər, yol xəritəsi və şəxsi plan.',
    name: 'Ad Soyad',
    namePh: 'Aysel Məmmədova',
    email: 'E-poçt',
    emailPh: 'sen@example.com',
    password: 'Şifrə',
    passwordPh: 'Ən azı 6 simvol',
    login: 'Daxil ol',
    register: 'Qeydiyyatdan keç',
    google: 'Google ilə davam et',
    or: 'və ya e-poçtla',
    oauthError: 'Google ilə giriş alınmadı. Yenidən cəhd et.',
    noAccount: 'Hesabın yoxdur?',
    haveAccount: 'Artıq hesabın var?',
    forgot: 'Şifrəni unutmusan?',
    forgotTitle: 'Şifrəni bərpa et',
    forgotSub: 'E-poçtunu yaz, sənə yeni şifrə təyin etmək üçün link göndərək.',
    sendLink: 'Link göndər',
    linkSentTitle: 'E-poçtuna bax',
    linkSentText: (email: string) => `${email} ünvanında hesab varsa, şifrəni yeniləmək üçün link göndərdik. Link 1 saat etibarlıdır.`,
    demoNoEmail: 'Demo rejimdə e-poçt göndərilmir. Supabase qoşulanda bu link real məktubla gələcək.',
    resetTitle: 'Yeni şifrə təyin et',
    resetSub: 'Hesabın üçün yeni şifrə yaz.',
    newPassword: 'Yeni şifrə',
    confirmPassword: 'Yeni şifrəni təkrarla',
    savePassword: 'Şifrəni yadda saxla',
    resetInvalid: 'Link etibarsızdır və ya vaxtı keçib. Yenisini istə.',
    requestNew: 'Yeni link istə',
    passwordsDiffer: 'Şifrələr eyni deyil.',
    passwordChanged: 'Şifrən yeniləndi ✓',
    backToLogin: 'Girişə qayıt',
    confirmTitle: 'E-poçtunu təsdiqlə',
    confirmText: (email: string) => `${email} ünvanına təsdiq linki göndərdik. Linkə keçəndən sonra daxil ola bilərsən.`,
    errors: {
      invalid_credentials: 'E-poçt və ya şifrə yanlışdır.',
      email_taken: 'Bu e-poçtla artıq hesab var. Daxil olmağa çalış.',
      weak_password: 'Şifrə çox zəifdir — ən azı 6 simvol olsun.',
      email_not_confirmed: 'Əvvəlcə e-poçtuna gələn linklə hesabını təsdiqlə.',
      not_allowed: 'Bu əməliyyata icazən yoxdur.',
      unknown: 'Nəsə alınmadı. Bir az sonra yenidən cəhd et.',
      nameRequired: 'Adını və soyadını yaz.',
      emailInvalid: 'E-poçt ünvanı düzgün görünmür.',
      passwordShort: 'Şifrə ən azı 6 simvol olmalıdır.',
    },
  },
  dash: {
    hello: (name: string) => (name ? `Salam, ${name} 👋` : 'Salam 👋'),
    sub: (open: number, fits: number) => (fits ? `Hazırda ${open} açıq fürsət var, ${fits}-i maraqlarına uyğundur.` : `Hazırda ${open} açıq fürsət var.`),
    saved: 'Saxlanılıb',
    applied: 'Müraciət edilib',
    accepted: 'Qəbul olunub',
    closing: 'Bu həftə bağlanır',
    upcoming: 'Yaxınlaşan son tarixlər',
    upcomingSub: 'Saxladığın, hələ müraciət etmədiyin fürsətlər',
    upcomingEmpty: 'Bəyəndiyin fürsəti saxla — son tarixi burada görünəcək və sənə xatırladacağıq.',
    allTracked: 'Hamısı',
    prep: (done: number, total: number) => `Hazırlıq ${done}/${total}`,
    findCta: 'Fürsət axtar',
    calendarCta: 'Təqvim',
    closingTitle: 'Tezliklə bağlanır',
    closingSub: 'Maraqlarına uyğun, son tarixi 14 gün içində olan və hələ saxlamadığın fürsətlər',
    shortcutsTitle: 'Qısayollar',
    guidesSub: 'Proqramlar və müraciət haqqında',
    aiSub: 'Məktub və müraciət yoxlanışı',
    greet: (part: 'morning' | 'day' | 'evening', name: string) =>
      `${part === 'morning' ? 'Sabahın xeyir' : part === 'day' ? 'Günortan xeyir' : 'Axşamın xeyir'}${name ? `, ${name}` : ''}`,
    nextTitle: 'Növbəti son tarix',
    nextDays: (d: number) => (d === 0 ? 'Bu gün!' : d === 1 ? 'Sabah' : `${d} gün`),
    nextLeft: 'qalıb',
    nextSaved: 'Saxladığın fürsət',
    nextSuggested: 'Sənə uyğun fürsət',
    nextNone: 'Yaxın son tarix yoxdur. Yeni fürsətlərə bax.',
    weekTitle: 'Növbəti 14 gün',
    weekSub: 'Hər gün neçə fürsətin son tarixidir. Narıncı — saxladıqların.',
    planTitle: 'Bu həftənin planı',
    planSub: 'Saxladığın fürsətlər üçün qalan hazırlıq addımları — burada işarələ.',
    planReady: 'Hazırlıq tamamdır — müraciət et!',
    planApply: 'Müraciət et',
    planEmpty: 'Bəyəndiyin fürsəti saxla — hazırlıq addımları burada plan kimi görünəcək.',
    programsTitle: 'Proqramlar',
    programsOpen: (n: number) => (n ? `${n} açıq fürsət` : 'Hazırda açıq fürsət yoxdur'),
    guidesTitle: 'Bələdçilər',
    badgesTitle: 'Nailiyyətlərin',
    badgesMore: 'Hamısına bax',
    profileStrength: (p: number) => `Profil ${p}%`,
  },
  notes: {
    title: 'Qeydlərim',
    sub: 'Yalnız sənin görəcəyin qeydlər: fikirlər, xatırlatmalar, müraciət planları.',
    ph: 'Yeni qeyd yaz… (məs.: "Cümə günü pasport üçün ASAN-a get")',
    add: 'Əlavə et',
    empty: 'Hələ qeyd yoxdur. İlk qeydini yuxarıda yaz.',
    pin: 'Sanc',
    unpin: 'Sancağı götür',
    edit: 'Redaktə et',
    remove: 'Sil',
    confirmRemove: 'Bu qeyd silinsin?',
    save: 'Yadda saxla',
    cancel: 'Ləğv et',
    color: 'Rəng',
    limit: 'Ən çox 100 qeyd saxlamaq olar. Köhnələrdən birini sil.',
    seeAll: 'Bütün qeydlər',
    count: (n: number) => `${n} qeyd`,
  },
  map: {
    title: 'Xəritə',
    sub: 'Fürsətlər ölkələr üzrə. Ölkəyə toxun — oradakı fürsətləri gör.',
    allCountries: 'Bütün ölkələr',
    online: 'Onlayn',
    count: (n: number) => `${n} fürsət`,
    countries: (n: number) => `${n} ölkə`,
    hint: 'Ölkəyə toxun — fürsətləri gör',
    kindLabel: 'Xəritə tipi',
    kinds: { standard: 'Standart', terrain: 'Relyef', satellite: 'Peyk', clean: 'Sadə' },
    empty: 'Bu ölkədə hazırda açıq fürsət yoxdur.',
    openList: 'Siyahıda aç',
    noKey: 'Xəritə hələ qoşulmayıb. Ölkəni aşağıdakı siyahıdan seç.',
    loadError: 'Xəritə yüklənmədi. Ölkəni aşağıdakı siyahıdan seç.',
    pick: 'Ölkə seç',
  },
  feed: {
    searchTitle: 'Bu gün hansı fürsəti axtarırsan?',
    searchPh: 'Məs.: gənclər mübadiləsi, İtaliya, ekologiya…',
    searchBtn: 'Axtar',
    tabs: { forYou: 'Sənin üçün', latest: 'Yeni əlavə olunanlar', closing: 'Son tarix yaxınlaşır' },
    featured: 'Günün fürsəti',
    empty: 'Bu bölmədə hələ fürsət yoxdur.',
    myDeadlines: 'Son tarixlərim',
    myDeadlinesEmpty: 'Saxladığın fürsətlərin son tarixləri burada görünəcək.',
    countries: 'Ölkələr üzrə',
    tips: 'Faydalı məsləhətlər',
    links: { profile: 'Profilim', cv: 'CV-m', tracker: 'Müraciətlərim' },
    aiSub: 'Məktub qaralaması və müraciət yoxlanışı',
    aiOpen: 'AI köməkçini aç',
  },
  home: {
    weekdays: ['Bazar', 'Bazar ertəsi', 'Çərşənbə axşamı', 'Çərşənbə', 'Cümə axşamı', 'Cümə', 'Şənbə'],
    brief: {
      lead: 'Bu həftə',
      deadlines: (n: number) => `${n} son tarixin`,
      mid: 'var, maraqlarına uyğun',
      fresh: (n: number) => `${n} yeni fürsət`,
      end: 'çıxıb.',
      calm: 'Bu həftə sakitdir — yeni fürsətlərə göz atmaq üçün yaxşı vaxtdır.',
    },
    profileRing: (p: number) => `Profil ${p}%`,
    deck: {
      title: 'Kəşf et',
      sub: 'Sənə uyğun fürsətlər, bir-bir. Bəyəndiyini saxla, qalanını keç.',
      skip: 'Keç',
      save: 'Saxla',
      more: 'Ətraflı',
      count: (i: number, n: number) => `${i} / ${n}`,
      doneTitle: 'Hamısına baxdın 🎉',
      doneSub: 'Yeni fürsətlər əlavə olunanda burada görünəcək.',
      reset: 'Keçdiklərimi yenidən göstər',
      browse: 'Bütün fürsətlər',
    },
    countdown: { title: 'Növbəti son tarix', none: 'Saxlanmış son tarix yoxdur.', noneCta: 'Fürsət saxla' },
    pipeline: { title: 'Müraciət yolum', rejected: (n: number) => `${n} imtina — bu da təcrübədir 💪` },
    todo: { title: 'Növbəti addımlar', sub: 'Saxladığın fürsətlər üçün hazırlıq — burada işarələ', empty: 'Hazırlıq tapşırığı yoxdur. Fürsət saxla — addımlar burada çıxacaq.' },
    timeline: { title: 'Növbəti 60 gün', sub: 'Narıncı — saxladıqların, yaşıl — sənə uyğun olanlar.', today: 'Bu gün' },
    programs: 'Proqramlar',
    guides: 'Oxumağa dəyər',
    searches: 'Axtarışların',
  },
  start: {
    title: 'Başlanğıc addımları',
    sub: (d: number, t: number) => `${d}/${t} tamamlanıb — Openly-dən ən çox faydanı belə görəcəksən`,
    done: 'Hamısı hazırdır! 🎉',
    hide: 'Gizlət',
    steps: {
      interests: 'Maraqlarını seç',
      profile: 'Şəkil və qısa təqdimat əlavə et',
      about: 'AI üçün "Haqqımda" yaz',
      save: 'İlk fürsəti saxla',
      search: 'Bir axtarışı yadda saxla',
      applied: 'Bir müraciəti "Müraciət edilib" et',
    },
  },
  aiHub: {
    title: 'AI müraciət köməkçisi',
    sub: 'Motivasiya məktubunu öz hekayənlə qur və göndərməzdən əvvəl komissiya gözü ilə yoxlat.',
    statusActive: 'Aktivdir',
    statusSoon: 'Tezliklə',
    statusLocked: 'Bu günlük bitdi',
    statusChecking: 'Yoxlanılır…',
    perDay: (n: number) => `Gündə ${n} istifadə`,
    letterTitle: 'Motivasiya məktubu köməkçisi',
    letterPoints: ['Elana uyğun 4–6 sual verir', 'Məktubun skeletini yalnız sənin cavablarından qurur', 'Uydurma fakt yox — boş yerlər [mötərizədə] qalır'],
    reviewTitle: 'Müraciət yoxlanışı',
    reviewPoints: ['Məktub və ya CV-ni yüklə (PDF, DOCX) və ya yapışdır', '1–10 uyğunluq balı və güclü tərəflər', 'Konkret düzəlişlər: sitat → problem → təklif'],
    pickTitle: 'Hansı fürsət üçün?',
    pickSub: 'AI hər dəfə konkret elanla işləyir. Saxladığın fürsətlərdən birini seç.',
    pickEmpty: 'Hələ fürsət saxlamamısan. Bəyəndiyin fürsəti saxla, sonra burada AI ilə hazırlaş.',
    pickFind: 'Fürsətlərə bax',
    write: 'Məktub yaz',
    review: 'Yoxlat',
    howTitle: 'Necə işləyir',
    how: [
      { title: 'Fürsəti seç', text: 'AI elanın mövzusunu, tələblərini və son tarixini oxuyur.' },
      { title: 'Suallara cavab ver', text: 'Öz real təcrübəni yaz — AI sənin yerinə fakt uydurmur.' },
      { title: 'Yoxlat və göndər', text: 'Qaralamanı öz səsinlə yenidən yaz, sonra AI ilə yoxlat.' },
    ],
    aboutTitle: 'AI səni nə qədər tanıyır?',
    aboutEmpty: 'Profilində "Haqqımda" boşdur. Təhsilini, təcrübəni və dillərini yaz — suallar və rəylər daha dəqiq olacaq.',
    aboutFilled: (n: number) => `"Haqqımda" doldurulub (${n} simvol). AI suallarını və rəylərini buna görə uyğunlaşdırır.`,
    aboutCta: 'Profili yenilə',
    lockedTitle: 'Pulsuz planda gündə 1 AI istifadəsi',
    lockedText: 'Bir məktub qaralaması və ya bir yoxlanış gündə pulsuzdur. Premium ilə gündə 15 — 3 ₼ / ay.',
    lockedCta: 'Premium-a bax',
    dashCta: 'AI köməkçini aç',
    dashNext: (title: string) => `Növbəti: "${title}" üçün məktub`,
  },
  student: {
    title: 'Tələbə',
    hubTitle: 'Xaricdə təhsil',
    hubSub: 'Təqaüdlər, universitetlər, müraciət yol xəritəsi və şəxsi planın — bir yerdə.',
    badge: '7 ₼ / ay',
    tabs: { roadmap: 'Yol xəritəsi', scholarships: 'Təqaüdlər', universities: 'Universitetlər', plan: 'Mənim planım', ai: 'AI məsləhətçi' },
    // paywall
    lockTitle: 'Openly Tələbə — xaricdə təhsilə yol',
    lockSub: 'Xaricdə bakalavr və ya magistr oxumaq istəyənlər üçün: hansı təqaüdə, hansı universitetə, nə vaxt və necə müraciət etməli.',
    lockItems: (sch: number, uni: number) => [
      `${sch} təqaüd: kim üçündür, nəyi qarşılayır, son tarixlər`,
      `${uni} universitet: ixtisaslar, təhsil haqqı, müraciət haqqı, tələblər`,
      '16 addımlıq müraciət yol xəritəsi — irəliləyişini qeyd et',
      'Mənim planım: balına və büdcənə uyğun universitetlər, müqayisə, saxladığın təqaüdlər və son tarixlər',
      'AI məsləhətçi: sənə uyğun təqaüd və universitetlər, esse yoxlanışı',
    ],
    lockCta: 'WhatsApp ilə Tələbə planı al',
    lockNote: 'WhatsApp-da 070 903 40 41 nömrəsinə yaz — ödənişdən sonra planı hesabında aktivləşdirəcəyik.',
    waMessage: (email: string) => `Salam! Openly Tələbə planını (7 ₼ / ay) almaq istəyirəm. Hesabım: ${email}`,
    lockGuest: 'Əvvəlcə pulsuz qeydiyyatdan keç',
    loadError: 'Məlumat yüklənmədi.',
    // profile (/student/profile)
    backToHub: 'Tələbə bölməsinə qayıt',
    profileTitle: 'Profilim',
    profileSub: 'Adın, fotun və qısa məlumatın. AI məsləhətçi "Haqqımda" mətnindən istifadə edir.',
    aboutHint: 'Təhsilin, balların, təcrübən, hədəfin — AI məsləhətçi tövsiyələrini buna görə verir.',
    aboutPh: 'Məs.: ADA Universiteti, kompüter elmləri, 3-cü kurs. GPA 3.6, IELTS 7.0. Magistrə Almaniyada data elmi üzrə getmək istəyirəm.',
    planTitle: 'Planım',
    planActive: 'Tələbə planı aktivdir 🎓',
    planActiveSub: 'Təqaüdlər, universitetlər, yol xəritəsi, planlayıcı və AI məsləhətçi açıqdır.',
    planLocked: 'Tələbə planı aktiv deyil',
    planLockedSub: 'Planı aktivləşdirəndə təqaüdlər, universitetlər, planlayıcı və AI məsləhətçi açılacaq.',
    planSeeInside: 'Nələr daxildir?',
    cancelPlan: 'Tələbə planını ləğv et',
    cancelPlanSub: 'Yol xəritəsindəki irəliləyişin və saxladıqların qalır, amma kataloq və AI bağlanacaq.',
    cancelPlanConfirm: 'Tələbə planı ləğv edilsin? Təqaüdlər, universitetlər və AI məsləhətçi bağlanacaq.',
    planCancelled: 'Tələbə planı ləğv edildi.',
    // roadmap
    progress: (d: number, t: number) => `${d}/${t} addım tamamlanıb`,
    phaseDone: (d: number, t: number) => `${d}/${t} tamamlanıb`,
    youAreHere: 'Buradasan',
    nextUp: 'Növbəti addım',
    allDone: 'Hamısı tamamlandı — uğurlar!',
    open: 'Aç',
    savedCount: (n: number) => `${n} təqaüd saxlanılıb`,
    // lists, cards and details
    search: 'Ad və ya ölkə üzrə axtar',
    filters: 'Filtrlər',
    openNow: 'İndi açıqdır',
    forMe: 'Mənə uyğun',
    forMeHint: 'Səviyyəni, ixtisasını və büdcəni “Mənim planım”da qeyd et — uyğun olanları işarələyək.',
    sort: 'Sırala',
    sortDeadline: 'Ən yaxın son tarix',
    sortName: 'Ad',
    sortCost: 'Ən ucuz',
    results: (n: number) => `${n} nəticə`,
    covers: { tuition: 'Təhsil haqqı', stipend: 'Aylıq təqaüd', housing: 'Yaşayış yeri', flights: 'Aviabilet', insurance: 'Sığorta', language: 'Dil kursu' },
    fullFunding: 'Tam təqaüd',
    partialFunding: 'Qismən təqaüd',
    closesToday: 'Bu gün bağlanır',
    openUntil: (m: string) => `Açıqdır · adətən bağlanır: ${m}`,
    closesIn: (m: string) => `Adətən bağlanır: ${m}`,
    opensIn: (m: string) => `Açılır: ${m}`,
    datesVary: 'Tarix dəyişir — ətraflıya bax',
    fitsYou: 'Sənə uyğundur',
    misses: { level: 'Səviyyən üçün deyil', field: 'İxtisasın üçün deyil', budget: 'Büdcədən bahadır' },
    save: 'Yadda saxla',
    saved: 'Saxlanılıb',
    details: 'Ətraflı',
    keyFacts: 'Əsas faktlar',
    compare: 'Müqayisə et',
    compareN: (n: number) => `Müqayisə et (${n})`,
    compareMax: 'Ən çox 3 universitet müqayisə etmək olar',
    compareTitle: 'Universitetləri müqayisə et',
    compareClear: 'Seçimi təmizlə',
    place: 'Yer',
    language: 'Tədris dili',
    from: (x: string) => `ən azı ${x}`,
    best: 'Ən sərfəli',
    // roadmap: steps the app ticks by itself
    auto: 'Avtomatik',
    autoHint: {
      goal: '“Mənim planım”da səviyyə və ixtisas seçəndə tamamlanır',
      language: '“Mənim planım”da IELTS balını qeyd edəndə tamamlanır',
      budget: '“Mənim planım”da illik büdcəni qeyd edəndə tamamlanır',
      shortlist: 'Siyahına 5 universitet əlavə edəndə tamamlanır',
      scholarships: 'Ən azı bir təqaüdü yadda saxlayanda tamamlanır',
      submit: 'Siyahında bir statusu “Müraciət edilib” edəndə tamamlanır',
      decide: 'Bir yerin statusunu “Qəbul olunub” edəndə tamamlanır',
    } as Record<string, string>,
    manualHint: 'Bunu özün qeyd et',
    // AI advisor
    aiSub: 'Sənin məlumatlarına və kataloqumuza əsaslanır. Qərar verməzdən əvvəl rəsmi səhifəni yoxla.',
    aiModes: { plan: 'Şəxsi plan', ask: 'Sual ver', review: 'Esseni yoxlat' },
    aiModeDesc: { plan: 'Sənə uyğun təqaüd, universitet və addımlar', ask: 'Təhsil və müraciət haqqında sual-cavab', review: 'Məktubunu seçdiyin yerə görə qiymətləndir' },
    aiLastPlan: (when: string) => `Son plan · ${when}`,
    aiYou: 'Sən',
    aiPlanIntro: 'Səviyyən, ixtisasın, IELTS, büdcə və profilindəki “Haqqımda” mətninə görə kataloqdan sənə uyğun təqaüd və universitetləri seçək, növbəti addımları aylar üzrə düzək.',
    aiPlanBtn: 'Planımı qur',
    aiAgain: 'Yenidən',
    aiNeedPrefs: 'Daha dəqiq nəticə üçün əvvəlcə “Mənim planım”da səviyyə, ixtisas, IELTS və büdcəni doldur.',
    aiRecSch: 'Tövsiyə olunan təqaüdlər',
    aiRecUni: 'Tövsiyə olunan universitetlər',
    aiSteps: 'Növbəti addımlar',
    aiRisks: 'Diqqət et',
    aiAskIntro: 'Xaricdə təhsil, təqaüd və müraciətlə bağlı istənilən sualını yaz.',
    aiAskPh: 'Sualını yaz…',
    aiAskBtn: 'Soruş',
    aiExamples: ['IELTS 6.0 ilə Avropada magistr oxumaq mümkündür?', 'Hansı təqaüdlər təhsil haqqını tam ödəyir?', 'Motivasiya məktubuna nə vaxt başlamalıyam?'],
    aiRelated: 'Kataloqda bax',
    aiFollowUp: 'Bunu da soruşa bilərsən',
    aiReviewIntro: 'Motivasiya məktubunu və ya esseni yapışdır — seçdiyin təqaüd və ya universitetin tələblərinə görə qiymətləndirək.',
    aiReviewFor: 'Kimə yazırsan?',
    aiReviewGeneral: 'Ümumi (konkret yer yoxdur)',
    aiFitBtn: 'AI: mən uyğunammı?',
    aiFitTitle: 'AI qiymətləndirməsi',
    aiVerdicts: { likely: 'Böyük ehtimalla uyğunsan', maybe: 'Ola bilər — yoxla', unlikely: 'Çətin görünür' } as Record<string, string>,
    aiPrepare: 'Hazırlamalı olduqların',
    aiCheck: 'Rəsmi səhifədə dəqiqləşdir',
    aiStudentOnly: 'AI məsləhətçi Tələbə planına daxildir.',
    // filters
    allFields: 'Bütün ixtisaslar',
    allCountries: 'Bütün ölkələr',
    allLevels: 'Bütün səviyyələr',
    anyField: 'İstənilən ixtisas',
    // scholarships
    coverage: 'Nəyi qarşılayır',
    eligibility: 'Kim müraciət edə bilər',
    howToApply: 'Necə müraciət etməli',
    deadline: 'Son tarix',
    officialPage: 'Rəsmi səhifə',
    noResults: 'Bu filtrlərə uyğun nəticə yoxdur.',
    // universities
    tuition: 'Təhsil haqqı',
    perYear: '/il',
    living: 'Yaşayış',
    perMonth: '/ay',
    appFee: 'Müraciət haqqı',
    free: 'Pulsuz',
    unknown: 'Proqramdan asılı',
    exams: 'İmtahanlar',
    requirements: 'Tələblər',
    scholarshipsNote: 'Təqaüd imkanları',
    addShortlist: 'Siyahıma əlavə et',
    inShortlist: 'Siyahımdadır',
    disclaimer: 'Məbləğlər və tarixlər təxminidir və hər il dəyişir — müraciətdən əvvəl rəsmi səhifədə yoxla.',
    // my plan
    myInfo: 'Mənim məlumatlarım',
    myInfoSub: 'Bununla sənə uyğun təqaüd və universitetləri işarələyirik. Profilində saxlanılır.',
    notSet: 'Seçilməyib',
    level: 'Səviyyə',
    field: 'İxtisas',
    ielts: 'IELTS balın',
    noIelts: 'Hələ yoxdur',
    budget: 'İllik büdcə',
    yearCost: 'Təxmini illik xərc',
    needIelts: (n: number) => `IELTS ${n} lazımdır`,
    fitUnis: 'Sənə uyğun universitet',
    fitSch: 'Sənə uyğun təqaüd',
    upcomingTitle: 'Yaxınlaşan son tarixlər',
    upcomingEmpty: 'Təqaüdləri yadda saxla və universitetləri siyahına əlavə et — son tarixləri burada görünəcək.',
    myList: 'Mənim siyahım',
    listEmptySch: 'Hələ təqaüd saxlamamısan.',
    listEmptyUni: 'Hələ universitet əlavə etməmisən.',
    feesTotal: 'Müraciət haqları cəmi',
    firstYear: 'İlk il təxmini xərc',
    remove: 'Siyahıdan çıxar',
    statuses: { planning: 'Planlaşdırılır', applied: 'Müraciət edilib', accepted: 'Qəbul olunub', rejected: 'İmtina' },
  },
  searches: {
    title: 'Saxladığın axtarışlar',
    save: 'Axtarışı saxla',
    namePh: 'Axtarışın adı',
    saveBtn: 'Saxla',
    cancel: 'Ləğv et',
    saved: 'Saxlanıldı — axtarış ana səhifəndə görünəcək.',
    limit: 'Ən çox 10 axtarış saxlamaq olar. Köhnəsini sil və yenidən cəhd et.',
    matches: (n: number) => `${n} fürsət`,
    fresh: (n: number) => `${n} yeni`,
    remove: 'Axtarışı sil',
    fallbackName: 'Axtarışım',
  },
  complete: {
    title: (p: number) => `Profilin ${p}% hazırdır`,
    sub: 'Tam profil sənə uyğun fürsətləri daha dəqiq seçməyə və AI köməkçiyə daha yaxşı məktub qurmağa kömək edir.',
    items: { photo: 'Şəkil', interests: 'Maraqlar', country: 'Ölkə', headline: 'Qısa təqdimat', about: 'Haqqımda', studies: 'Təhsil / iş', languages: 'Dillər' },
    cta: 'Profili tamamla',
  },
  newHere: 'Yeni başlayırsan? Proqramlar və müraciət haqqında qısa bələdçilərə bax.',
  prep: {
    title: 'Müraciət hazırlığı',
    items: {
      cv: 'CV hazırdır',
      letter: 'Motivasiya məktubu yazılıb',
      passport: 'Pasportun müddəti yoxlanılıb',
      sending_org: 'Göndərən təşkilatla əlaqə saxlanılıb',
      form: 'Müraciət forması doldurulub',
    },
    note: 'Qeydlərim',
    notePh: 'Məs.: "Bazar ertəsi təşkilata yazdım, cavab gözləyirəm"',
    noteSaved: 'Yadda saxlanıldı ✓',
  },
  trip: {
    title: 'Səfərə hazırlıq',
    items: {
      infopack: 'İnfo-paket oxunub, təşkilatçıya cavab verilib',
      visa: 'Viza üçün sənədlər verilib / viza alınıb',
      insurance: 'Səyahət sığortası alınıb',
      tickets: 'Biletlər alınıb, qəbzlər saxlanılıb (geri ödəniş üçün)',
      youthpass: 'Sonda Youthpass sertifikatı alınacaq',
    },
  },
  age: {
    ok: (range: string) => `Yaşın bu növ proqrama uyğundur (adətən ${range}).`,
    young: (range: string) => `Diqqət: bu növ proqramlar adətən ${range} yaş üçündür — şərtləri yoxla.`,
    old: (range: string) => `Diqqət: bu növ proqramlar adətən ${range} yaş üçündür — şərtləri yoxla.`,
    unknown: (range: string) => `Bu növ proqramlar adətən ${range} yaş üçündür. Profildə doğum ilini yaz ki, avtomatik yoxlayaq.`,
    plus: (min: number) => `${min}+`,
  },
  similar: {
    title: 'Oxşar fürsətlər',
  },
  list: {
    title: 'Fürsətlər',
    allTitle: 'Bütün fürsətlər',
    picked: 'Sənin üçün seçilmişlər',
    seeAll: 'Hamısına bax',
    filters: 'Filtrlər',
    sub: (n: number) => `${n} açıq fürsət`,
    results: (n: number) => `${n} nəticə`,
    search: 'Ad, proqram və ya ölkə üzrə axtar…',
    forYou: 'Mənim maraqlarım',
    allPrograms: 'Bütün proqramlar',
    allKinds: 'Bütün növlər',
    allCountries: 'Bütün ölkələr',
    online: 'Onlayn',
    closingSoon: 'Son 7 gün',
    fullyFunded: 'Xərclər qarşılanır',
    showClosed: 'Bağlananları da göstər',
    clear: 'Filtrləri təmizlə',
    empty: 'Bu filtrlərə uyğun fürsət tapılmadı.',
    noInterests: 'Maraqlarını seçsən, sənə uyğun fürsətləri ayırarıq.',
    pickInterests: 'Maraqları seç',
    draft: 'Qaralama',
    earlyTeaser: (n: number) => `Premium istifadəçilər ${n} yeni fürsəti artıq görür. Sən ${n === 1 ? 'onu' : 'onları'} 24 saat sonra görəcəksən.`,
    seePremium: 'Premium-a bax',
    premiumFilter: 'Bu filtr Premium-dadır',
    newBadge: 'Yeni',
    sortBest: 'Ən uyğun',
    sortDeadline: 'Son tarix',
    match: (n: number) => `${n}% uyğun`,
    matchReasons: { interests: 'maraqlarına uyğun', funded: 'xərclər qarşılanır', partlyFunded: 'xərclər qismən qarşılanır', online: 'onlayn', country: 'sənin ölkəndə', kind: 'sevdiyin növ', destination: 'getmək istədiyin ölkə' },
    forYouTitle: (n: number) => (n === 1 ? 'Sənə uyğun 1 yeni imkan var' : `Sənə uyğun ${n} yeni imkan var`),
    forYouSoon: (d: number) => (d <= 0 ? 'biri bu gün bağlanır' : d === 1 ? 'biri sabah bağlanır' : `birinin son tarixi ${d} gündür`),
  },
  card: {
    save: 'Saxla',
    saved: 'Saxlanılıb',
    closed: 'Bağlanıb',
    deadline: 'Son tarix',
  },
  detail: {
    notFound: 'Fürsət tapılmadı və ya artıq mövcud deyil.',
    apply: 'Rəsmi səhifədə müraciət et',
    applyHint: 'Müraciət rəsmi mənbədə edilir. Müraciət edəndən sonra statusu burada yenilə.',
    track: 'Müraciətlərimə əlavə et',
    remove: 'Siyahıdan çıxar',
    status: 'Status',
    about: 'Haqqında',
    when: 'Tarixlər',
    where: 'Yer',
    type: 'Növ',
    costs: 'Xərclər',
    program: 'Proqram',
    organizer: 'Təşkilatçı',
    interests: 'Mövzular',
    sendingOrg: 'Azərbaycandan göndərən təşkilat',
    sendingOrgHint: 'Bu proqrama birbaşa yox, bu təşkilat vasitəsilə müraciət olunur. Əlaqə saxla:',
  },
  tracker: {
    title: 'Müraciətlərim',
    sub: 'Saxladığın və müraciət etdiyin fürsətlər bir yerdə.',
    all: 'Hamısı',
    empty: 'Hələ heç nə saxlamamısan.',
    emptyCta: 'Fürsətlərə bax',
    usage: (n: number) => `Pulsuz plan: ${n} / ${FREE_EVENT_LIMIT} fürsət`,
    upgrade: 'Limitsiz izləmə üçün Premium — 3 ₼ / ay',
    confirmRemove: (title: string) => `"${title}" siyahıdan çıxarılsın? Hazırlıq qeydləri və checklist də silinəcək.`,
  },
  limit: {
    title: 'Pulsuz plan limiti',
    text: `Pulsuz planda eyni anda ${FREE_EVENT_LIMIT} fürsət izləyə bilərsən. Yenisini əlavə etmək üçün birini siyahıdan çıxar və ya Premium-a keç.`,
    ok: 'Aydındır',
    manage: 'Müraciətlərimə keç',
  },
  profile: {
    title: 'Profil',
    onboardingTitle: 'Səni tanıyaq 👋',
    onboardingSub: 'Maraqlarını seç ki, sənə uyğun fürsətləri ön plana çıxaraq. Sonra dəyişə bilərsən.',
    name: 'Ad Soyad',
    email: 'E-poçt',
    country: 'Yaşadığın ölkə',
    countryPh: 'Seç…',
    interests: 'Maraq sahələri',
    interestsHint: 'Bir neçəsini seçə bilərsən',
    plan: 'Plan',
    basic: 'Pulsuz',
    premium: 'Premium',
    student: 'Tələbə',
    save: 'Yadda saxla',
    continue: 'Davam et',
    saved: 'Yadda saxlanıldı ✓',
    about: 'Haqqımda',
    aboutHint: 'Təhsil, təcrübə, bacarıqlar, könüllülük keçmişi. AI köməkçisi məktub hazırlayanda bundan istifadə edir.',
    aboutPh: 'Məs.: ADA Universiteti, 3-cü kurs, beynəlxalq münasibətlər. 2 il "Gənclər Evi"ndə könüllü, ekologiya kampaniyaları təşkil etmişəm. İngilis dili B2.',
    photo: 'Profil şəkli',
    changePhoto: 'Şəkli dəyiş',
    removePhoto: 'Sil',
    photoHint: 'JPG, PNG və ya WEBP. Kvadrat kəsilir.',
    photoError: 'Şəkil yüklənmədi. Başqa şəkil seç (JPG, PNG, WEBP).',
    headline: 'Qısa təqdimat',
    headlinePh: 'Məs.: Tələbə · ADA Universiteti · Ekologiya könüllüsü',
    tabProfile: 'Profil',
    tabPremium: 'Plan',
    tabSettings: 'Parametrlər',
    security: 'Şifrəni dəyiş',
    securityHint: 'Google ilə daxil olursansa, burada e-poçtla giriş üçün şifrə də təyin edə bilərsən.',
    notifications: 'E-poçt bildirişləri',
    digest: 'Yeni fürsətlər haqqında xülasə',
    digestFree: 'Həftədə 1 dəfə (bazar ertəsi) — maraqlarına uyğun yeni fürsətlər.',
    digestPremium: 'Hər gün — maraqlarına uyğun yeni fürsətlər.',
    reminders: 'Son tarix xatırlatmaları',
    remindersPremium: 'Saxladığın fürsətin son tarixinə 7, 3 və 1 gün qalanda.',
    remindersFree: 'Yalnız Premium-da. Premium — 3 ₼ / ay.',
    sectionBasics: 'Əsas məlumat',
    sectionBasicsSub: 'Digər iştirakçılar və AI səni belə görür.',
    sectionInterests: 'Maraq sahələri',
    sectionInterestsSub: (n: number) => (n ? `${n} seçilib — tövsiyələr və e-poçt xülasəsi buna görə seçilir.` : 'Seçdiklərinə görə fürsətləri ön plana çıxarırıq.'),
    sectionAbout: 'AI üçün haqqımda',
    sectionAboutSub: 'AI köməkçi suallarını və rəylərini bu mətnə görə uyğunlaşdırır. Nə qədər konkret, o qədər yaxşı.',
    aboutCount: (n: number) => `${n} / 2000`,
    aboutTipsLabel: 'Əlavə et:',
    aboutTips: [
      { label: 'Təhsil', text: 'Təhsil: ' },
      { label: 'Təcrübə', text: 'Könüllülük / iş təcrübəsi: ' },
      { label: 'Dillər', text: 'Dillər: ' },
      { label: 'Bacarıqlar', text: 'Bacarıqlar: ' },
      { label: 'Hədəf', text: 'Niyə beynəlxalq proqramlara qatılmaq istəyirəm: ' },
    ],
    unsaved: 'Yadda saxlanmamış dəyişikliklər var',
    statSaved: 'saxlanılıb',
    statApplied: 'müraciət',
    statAccepted: 'qəbul',
    completeness: (p: number) => `Profil ${p}% hazırdır`,
    language: 'Dil',
    languageSub: 'Saytın dili.',
    account: 'Hesab',
    accountEmail: 'E-poçt',
    accountType: 'Hesab növü',
    accountRegular: 'Adi hesab',
    accountStudent: 'Tələbə hesabı',
    logout: 'Hesabdan çıx',
    logoutSub: 'Bu cihazda hesabdan çıxacaqsan.',
    tabJourney: 'Mənim yolum',
    tabMatch: 'Tərcihlər',
    theme: 'Profil rəngi',
    birthYear: 'Doğum ili',
    birthYearHint: 'yaş limitlərini yoxlamaq üçün',
    birthYearPh: 'Seç…',
    occupation: 'Hazırda',
    occupations: { school: 'Məktəbliyəm', student: 'Tələbəyəm', graduate: 'Məzunam', working: 'İşləyirəm', other: 'Digər' },
    school: 'Məktəb / universitet / iş yeri',
    schoolPh: 'Məs.: ADA Universiteti',
    field: 'İxtisas / sahə',
    fieldPh: 'Məs.: Beynəlxalq münasibətlər',
    linkedin: 'LinkedIn (istəyə bağlı)',
    sectionLanguages: 'Dillər',
    sectionLanguagesSub: 'Proqramların çoxu ingilis dilindədir — səviyyəni dürüst göstər.',
    languageName: 'Dil',
    languagePh: 'Məs.: İngilis',
    languageLevel: 'Səviyyə',
    levelNative: 'Ana dili',
    addLanguage: 'Dil əlavə et',
    languageSuggestions: ['Azərbaycan', 'İngilis', 'Rus', 'Türk', 'Alman', 'Fransız', 'İspan', 'İtalyan'],
    sectionSkills: 'Bacarıqlar',
    sectionSkillsSub: 'CV-ndə və AI rəylərində istifadə olunur. Enter ilə əlavə et.',
    skillPh: 'Bacarıq yaz və Enter bas…',
    skillSuggestions: ['Komanda işi', 'Liderlik', 'İctimai çıxış', 'Layihə idarəetməsi', 'Tədbir təşkili', 'Fotoqrafiya', 'Video montaj', 'Qrafik dizayn', 'SMM', 'Tərcümə'],
    sectionExperience: 'Təcrübə',
    sectionExperienceSub: 'Keçmiş mübadilələr, könüllülük, layihələr. Xaricdəkilər "pasportuna" möhür kimi düşür.',
    expTitle: 'Nə idi?',
    expTitlePh: 'Məs.: Gənclər mübadiləsi "Green Minds"',
    expOrg: 'Təşkilat',
    expYear: 'İl',
    expCountry: 'Ölkə',
    addExperience: 'Təcrübə əlavə et',
    remove: 'Sil',
  },
  prefsTab: {
    title: 'Sənə nə uyğundur?',
    sub: 'Bu seçimlər "Sənin üçün" siyahısını, uyğunluq faizini və tövsiyələri dəyişir. Hər dəyişiklik dərhal yadda qalır.',
    kinds: 'Hansı növlər maraqlıdır?',
    kindsHint: 'Heç biri seçilməsə, hamısı göstərilir.',
    duration: 'Müddət',
    durations: { short: 'Qısa', long: 'Uzun', any: 'Fərq etmir' },
    durationsSub: { short: '5–21 gün: mübadilə, təlim', long: '2–12 ay: könüllülük', any: 'Hər ikisi' },
    funded: 'Yalnız xərcləri tam qarşılanan',
    fundedSub: 'Digərləri tövsiyələrdə aşağı düşür.',
    passport: 'Etibarlı xarici pasportum var',
    passportSub: 'Yoxdursa, müraciət hazırlığında xatırladacağıq.',
    destinations: 'Getmək istədiyin ölkələr',
    destinationsHint: 'Bu ölkələrdəki fürsətlər önə çıxır.',
    saved: 'Yadda saxlanıldı ✓',
  },
  journey: {
    statsTitle: 'Müraciət statistikam',
    total: 'Müraciət',
    accepted: 'Qəbul',
    rate: 'Qəbul faizi',
    badgesTitle: 'Nailiyyətlər',
    badgesSub: (n: number, t: number) => `${t}-dən ${n}-i qazanılıb`,
    badges: {
      first_save: { name: 'İlk addım', how: 'İlk fürsəti saxla' },
      first_apply: { name: 'Cəsarətli', how: 'İlk müraciəti et' },
      five_apply: { name: 'Qətiyyətli', how: '5 müraciət et' },
      accepted: { name: 'Qəbul olundum!', how: 'Bir proqrama qəbul ol' },
      profile: { name: 'Tam profil', how: 'Profili 100% doldur' },
      polyglot: { name: 'Poliqlot', how: '3 və ya daha çox dil əlavə et' },
      traveller: { name: 'Səyyah', how: '3 ölkədə iştirak et' },
      resilient: { name: 'Dözümlü', how: 'İmtinadan sonra davam et' },
    },
    passportTitle: 'Səyahət pasportum',
    passportSub: 'Qəbul olunduğun proqramların və təcrübələrinin ölkələri.',
    passportEmpty: 'Hələ möhür yoxdur. Qəbul olunduğun proqramlar və "Təcrübə" bölməsindəki xarici ölkələr burada görünəcək.',
    cvTitle: 'Könüllü CV-n',
    cvSub: 'Profilindən avtomatik qurulur: təhsil, dillər, bacarıqlar, təcrübə. PDF kimi yüklə və müraciətə əlavə et.',
    cvCta: 'CV-yə bax',
  },
  cv: {
    title: 'Könüllü CV',
    back: 'Profilə qayıt',
    print: 'PDF kimi yüklə / çap et',
    printHint: 'Çap pəncərəsində "PDF kimi saxla"nı seç.',
    edit: 'Profili redaktə et',
    empty: 'CV üçün məlumat azdır. Profildə təhsil, dillər, bacarıqlar və təcrübəni doldur.',
    contact: 'Əlaqə',
    about: 'Haqqımda',
    education: 'Təhsil / məşğuliyyət',
    languages: 'Dillər',
    skills: 'Bacarıqlar',
    experience: 'Təcrübə',
    openly: 'Openly vasitəsilə qəbul olunduğum proqramlar',
    interests: 'Maraq sahələri',
    born: (y: number) => `Doğum ili: ${y}`,
  },
  guest: {
    listBanner: 'Pulsuz qeydiyyatdan keç: fürsətləri saxla, müraciətlərini izlə, sənə uyğun olanları gör.',
    signUp: 'Qeydiyyat',
    logIn: 'Daxil ol',
    sidebar: 'Fürsətləri saxlamaq və müraciətləri izləmək üçün pulsuz hesab yarat.',
    aiText: 'AI müraciət köməkçisi hesabı olanlar üçündür: pulsuz planda gündə 1 istifadə, Premium-da 15. Əvvəlcə pulsuz qeydiyyatdan keç.',
  },
  share: {
    title: 'Paylaş',
    copy: 'Linki kopyala',
    copied: 'Kopyalandı ✓',
    calendar: 'Son tarixi təqvimə əlavə et',
    google: 'Google Təqvim',
    ics: 'Apple / Outlook (.ics)',
    eventTitle: (title: string) => `Son tarix: ${title}`,
    text: (title: string, date: string) => `${title} — son tarix ${date}`,
  },
  applied: {
    question: 'Müraciət etdin?',
    text: 'Etdinsə, statusu "Müraciət edilib" edək ki, izləmək rahat olsun.',
    yes: 'Bəli, müraciət etdim',
    no: 'Hələ yox',
  },
  peers: {
    title: 'Qəbul olunan digər iştirakçılar',
    sub: 'Eyni proqrama qəbul olunanlarla tanış ol: yol, viza və yaşayış üçün birlikdə planlaşdırın.',
    share: 'Adımı və e-poçtumu bu proqrama qəbul olunan digərləri ilə paylaş',
    none: 'Hələ ki əlaqəsini paylaşan başqa iştirakçı yoxdur. Kimsə qoşulan kimi burada görünəcək.',
  },
  ai: {
    title: 'AI müraciət köməkçisi',
    sub: 'Motivasiya məktubunu öz hekayənlə hazırla və göndərməzdən əvvəl yoxlat.',
    open: 'AI köməkçini aç',
    locked: 'Pulsuz planda gündə 1 AI istifadəsi var. Premium ilə gündə 15.',
    tabLetter: 'Motivasiya məktubu',
    tabReview: 'Müraciəti yoxlat',
    // Short tab labels for phones.
    tabLetterShort: 'Məktub',
    tabReviewShort: 'Yoxlat',
    comingSoon: 'AI köməkçi tezliklə aktiv olacaq. Hər şey hazırdır — işə düşən kimi burada istifadə edə biləcəksən.',
    letterIntro: 'AI hazır məktub yazmır. Əvvəlcə sənə bu elana uyğun suallar verir, sonra yalnız sənin cavablarından məktubun skeletini qurur. Son sözü sən yazırsan.',
    start: 'Sualları hazırla',
    thinking: 'AI düşünür…',
    answerPh: 'Konkret yaz: nə etdin, harada, nə öyrəndin…',
    letterLang: 'Məktubun dili',
    makeDraft: 'Qaralama hazırla',
    needAnswers: 'Ən azı bir suala cavab yaz.',
    draftTitle: 'Qaralama',
    draftNote: 'Bu, başlanğıc nöqtəsidir. [Kvadrat mötərizədəki] yerləri doldur və məktubu öz səsinlə yenidən yaz — komissiyalar şablon məktubları tez tanıyır.',
    copy: 'Kopyala',
    copied: 'Kopyalandı ✓',
    tips: 'Göndərməzdən əvvəl',
    missing: 'Əlavə etməli olduğun məlumat',
    again: 'AI ilə yenidən başla',
    writeMyself: 'Özüm yazacam',
    myLetter: 'Motivasiya məktubum',
    letterPh: 'Məktubunu bura yaz və ya yapışdır…',
    saveLetter: 'Yadda saxla',
    unsaved: 'Yadda saxlanmamış dəyişikliklər var',
    savedAt: (when: string) => `Yadda saxlanılıb · ${when}`,
    reviewIntro: 'Məktubunu və ya CV-ni fayl kimi yüklə, ya da mətnini yapışdır. AI onu bu elanın tələbləri ilə müqayisə edib konkret rəy verəcək.',
    docType: 'Sənəd',
    docLetter: 'Motivasiya məktubu',
    docCv: 'CV',
    reviewPh: 'Mətni bura yapışdır (ən azı 50 simvol)…',
    upload: 'Fayl yüklə',
    uploadHint: 'PDF, DOCX və ya TXT, 3 MB-a qədər. Ya da mətni aşağıya yapışdır.',
    fromFile: (name: string) => `Mətn "${name}" faylından götürüldü — göndərməzdən əvvəl düzəldə bilərsən.`,
    pdfAttached: 'PDF olduğu kimi yoxlanacaq (dizayn və skan edilmiş səhifələr daxil).',
    removeFile: 'Faylı çıxar',
    fileType: 'Bu fayl növü dəstəklənmir. PDF, DOCX və ya TXT seç (köhnə .doc-u Word-də .docx kimi saxla).',
    fileTooBig: 'Fayl çox böyükdür (maksimum 3 MB).',
    fileRead: 'Faylı oxumaq alınmadı. Başqa fayl seç və ya mətni yapışdır.',
    reviewBtn: 'Yoxla',
    tooShort: 'Mətn çox qısadır (ən azı 50 simvol).',
    score: 'Uyğunluq balı',
    strengths: 'Güclü tərəflər',
    issues: 'Düzəltməli olduğun yerlər',
    suggestion: 'Təklif',
    missingTitle: 'Komissiya bunu axtaracaq',
    remaining: (n: number) => `Bu gün ${n} AI istifadəsi qalıb`,
    quota: (r: number, l: number) => `Bu gün ${l}-dən ${r} AI istifadəsi qalıb`,
    freeNote: 'Pulsuz plan: gündə 1. Premium ilə gündə 15 →',
    errors: {
      premium_required: 'AI köməkçi bu hesab üçün əlçatan deyil.',
      student_required: 'AI məsləhətçi Tələbə planına daxildir.',
      daily_limit: 'Bu günkü AI limitinə çatdın (pulsuz: gündə 1, Premium: 15). Sabah yenidən cəhd et.',
      refused: 'AI bu sorğunu emal edə bilmədi. Mətni dəyişib yenidən cəhd et.',
      ai_unavailable: 'AI köməkçi hazırda əlçatan deyil. Bir az sonra yenidən cəhd et.',
      not_configured: 'AI köməkçi tezliklə aktiv olacaq.',
      unknown: 'Nəsə alınmadı. Yenidən cəhd et.',
    },
  },
  premium: {
    title: 'Premium',
    sub: 'Heç bir fürsəti qaçırmamaq istəyənlər üçün.',
    current: 'Sənin planın',
    active: 'Premium aktivdir ✦',
    free: 'Pulsuz',
    price: '3 ₼ / ay',
    feature: 'Xüsusiyyət',
    rows: [
      { name: 'Fürsətlər siyahısı, axtarış, maraq və ölkə filtrləri', free: true, premium: true },
      { name: 'Eyni anda izlənən fürsətlər', free: '3', premium: 'Limitsiz' },
      { name: 'Yeni fürsətlər haqqında e-poçt xülasəsi', free: 'Həftəlik', premium: 'Gündəlik' },
      { name: 'Yeni fürsətlərə erkən giriş (24 saat əvvəl)', free: false, premium: true },
      { name: 'Təkmil filtrlər: xərclər qarşılanır, son 7 gün', free: false, premium: true },
      { name: 'Son tarix xatırlatmaları (7, 3, 1 gün əvvəl)', free: false, premium: true },
      { name: 'Ağıllı uyğunlaşdırma: hər fürsət üçün uyğunluq faizi', free: false, premium: true },
      { name: 'AI köməkçi: məktub qaralaması və müraciət yoxlanışı', free: 'Gündə 1', premium: 'Gündə 15' },
    ],
    cta: 'WhatsApp ilə Premium al',
    ctaNote: 'WhatsApp-da 070 903 40 41 nömrəsinə yaz — ödənişdən sonra Premium-u hesabında aktivləşdirəcəyik.',
    waMessage: (email: string) => `Salam! Openly Premium (3 ₼ / ay) almaq istəyirəm. Hesabım: ${email}`,
    activeSub: 'Bütün Premium imkanları açıqdır: limitsiz izləmə, erkən giriş, xatırlatmalar, ağıllı uyğunlaşdırma və AI köməkçi.',
    cancelTitle: 'Premium-u ləğv et',
    cancelSub: 'Pulsuz plana keçəcəksən. Saxladığın fürsətlər qalır, amma yenilərini yalnız 3-ə qədər izləyə biləcəksən.',
    cancelBtn: 'Premium-u ləğv et',
    cancelConfirm: 'Premium ləğv edilsin? AI köməkçi, xatırlatmalar və limitsiz izləmə bağlanacaq.',
    cancelled: 'Premium ləğv edildi. İndi pulsuz plandasan.',
    studentActive: 'Tələbə planı aktivdir 🎓',
    studentActiveSub: 'Premium-un bütün imkanları və tələbə bölməsi açıqdır: təqaüdlər, universitetlər, yol xəritəsi və planlayıcı.',
    openStudent: 'Tələbə bölməsinə keç',
    studentUpsellTitle: 'Xaricdə oxumaq istəyirsən? Openly Tələbə — 7 ₼ / ay',
    studentUpsellText: 'Premium-un hər şeyi, üstəlik təqaüdlər, universitetlər (ixtisas, təhsil və müraciət haqqı), 16 addımlıq yol xəritəsi və xərc planlayıcısı.',
    studentUpsellCta: 'Nələr daxildir?',
  },
  users: {
    title: 'İstifadəçilər',
    sub: (n: number, p: number, st: number) => `${n} istifadəçi · ${p} Premium · ${st} Tələbə`,
    confirmPlan: (email: string, plan: string) => `${email} → ${plan} planı?`,
    planLabel: 'Plan',
    typeLabel: 'Hesab növü',
    typeRegular: 'Adi',
    typeStudent: 'Tələbə',
    confirmType: (email: string, type: string) => `${email} → ${type} hesabı? Bu növdə olmayan plan pulsuz plana qayıdacaq.`,
    search: 'Ad və ya e-poçt üzrə axtar…',
    joined: 'Qoşulub',
    admin: 'Admin',
    empty: 'İstifadəçi tapılmadı.',
  },
  admin: {
    title: 'Fürsətləri idarə et',
    sub: 'Əlavə et, redaktə et, dərc et və ya gizlət.',
    add: 'Yeni fürsət',
    edit: 'Redaktə',
    delete: 'Sil',
    confirmDelete: (title: string) => `“${title}” silinsin? Bu geri qaytarıla bilməz.`,
    published: 'Dərc olunub',
    draft: 'Qaralama',
    empty: 'Hələ fürsət yoxdur. İlkini əlavə et.',
    newTitle: 'Yeni fürsət',
    editTitle: 'Fürsəti redaktə et',
    f: {
      title: 'Başlıq',
      program: 'Proqram',
      otherProgram: 'Proqramın adı',
      organizer: 'Təşkilatçı',
      sendingOrg: 'Göndərən təşkilat (AZ)',
      sendingOrgHint: 'Gənclər mübadilələri üçün: müraciət bu təşkilat vasitəsilə olunur.',
      sendingOrgContact: 'Göndərən təşkilatın əlaqəsi (e-poçt, telefon və ya sayt)',
      kind: 'Növ',
      country: 'Ölkə',
      city: 'Şəhər',
      online: 'Onlayn keçirilir',
      interests: 'Mövzular',
      deadline: 'Müraciət son tarixi',
      start: 'Başlama tarixi',
      end: 'Bitmə tarixi',
      costs: 'Xərclər',
      url: 'Rəsmi link',
      description: 'Təsvir',
      publish: 'Dərc et (istifadəçilər görsün)',
      save: 'Yadda saxla',
      cancel: 'Ləğv et',
      required: 'Bu sahə vacibdir.',
      badUrl: 'Link https:// ilə başlamalıdır.',
      badDates: 'Bitmə tarixi başlamadan əvvəl ola bilməz.',
    },
  },
  daysLeft: (d: number) => (d < 0 ? 'Bağlanıb' : d === 0 ? 'Bu gün bitir' : d === 1 ? 'Sabah bitir' : `${d} gün qaldı`),
};

type AppText = typeof az;

const en: AppText = {
  demoBanner: 'Demo mode: data is stored only in this browser.',
  demoLogin: 'Log in with a demo account',
  demoAdmin: 'Admin',
  demoUser: 'User',
  demoStudent: 'Student',
  loading: 'Loading…',
  retry: 'Try again',
  loadError: 'Couldn’t load the data.',
  close: 'Close',
  saveError: 'Couldn’t save. Please try again.',
  back: 'Back',
  navGroups: { explore: 'Explore', mine: 'My stuff' },
  learn: {
    title: 'Guides',
    sub: 'How the programmes work, how to apply, how to get ready to travel — short and simple.',
    programsTitle: 'Programmes',
    guidesTitle: 'Step-by-step guides',
    minutes: (n: number) => `${n} min read`,
    sources: 'Official sources',
    related: 'More guides',
    browse: 'See matching opportunities',
    allGuides: 'All guides',
    useful: 'Useful reading',
  },
  program: {
    about: 'What is it?',
    who: 'Who it’s for',
    costs: 'Costs',
    open: (n: number) => `${n} open opportunit${n === 1 ? 'y' : 'ies'}`,
    none: 'There are no open opportunities in this programme right now. You’ll see new ones in your weekly digest.',
    official: 'Official website',
    more: 'About the programme',
  },
  calendar: {
    title: 'Deadline calendar',
    sub: 'Every opportunity’s application deadline at a glance.',
    today: 'Today',
    prev: 'Previous month',
    next: 'Next month',
    onlyMine: 'Only my saved ones',
    empty: 'No deadlines this month.',
    more: (n: number) => `+${n} more`,
    nextDeadline: (d: number, month: string) => `Next deadline: ${month} ${d}`,
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  },
  nav: { student: 'Student', calendar: 'Calendar', guides: 'Guides', opportunities: 'Opportunities', tracker: 'My applications', profile: 'Profile', admin: 'Admin', users: 'Users', premium: 'Premium', logout: 'Log out', home: 'Home', ai: 'AI assistant', map: 'Map' },
  auth: {
    loginTitle: 'Welcome back',
    loginSub: 'Log in to keep tracking your opportunities.',
    registerTitle: 'Create your account',
    registerSub: 'It’s free. Pick your interests and see matching opportunities.',
    accountType: 'Account type',
    typeRegular: 'Regular account',
    typeStudent: 'Student account',
    studentLoginSub: 'Log in to your student account: scholarships, universities and your study roadmap.',
    studentRegisterSub: 'A separate account for studying abroad: scholarships, universities, a roadmap and your own plan.',
    name: 'Full name',
    namePh: 'Aysel Mammadova',
    email: 'Email',
    emailPh: 'you@example.com',
    password: 'Password',
    passwordPh: 'At least 6 characters',
    login: 'Log in',
    register: 'Sign up',
    google: 'Continue with Google',
    or: 'or with email',
    oauthError: 'Google sign-in didn’t work. Please try again.',
    noAccount: 'No account yet?',
    haveAccount: 'Already have an account?',
    forgot: 'Forgot your password?',
    forgotTitle: 'Reset your password',
    forgotSub: 'Enter your email and we’ll send you a link to set a new password.',
    sendLink: 'Send link',
    linkSentTitle: 'Check your email',
    linkSentText: (email: string) => `If an account exists for ${email}, we sent a link to reset your password. It’s valid for 1 hour.`,
    demoNoEmail: 'Demo mode doesn’t send emails. Once Supabase is connected this link arrives by email.',
    resetTitle: 'Set a new password',
    resetSub: 'Choose a new password for your account.',
    newPassword: 'New password',
    confirmPassword: 'Repeat new password',
    savePassword: 'Save password',
    resetInvalid: 'This link is invalid or has expired. Request a new one.',
    requestNew: 'Request a new link',
    passwordsDiffer: 'Passwords don’t match.',
    passwordChanged: 'Password updated ✓',
    backToLogin: 'Back to log in',
    confirmTitle: 'Confirm your email',
    confirmText: (email: string) => `We sent a confirmation link to ${email}. Open it, then log in.`,
    errors: {
      invalid_credentials: 'Wrong email or password.',
      email_taken: 'An account with this email already exists. Try logging in.',
      weak_password: 'Password is too weak — use at least 6 characters.',
      email_not_confirmed: 'Please confirm your account using the link in your email first.',
      not_allowed: 'You’re not allowed to do that.',
      unknown: 'Something went wrong. Please try again in a moment.',
      nameRequired: 'Please enter your full name.',
      emailInvalid: 'That email address doesn’t look right.',
      passwordShort: 'Password must be at least 6 characters.',
    },
  },
  dash: {
    hello: (name: string) => (name ? `Hi, ${name} 👋` : 'Hi 👋'),
    sub: (open: number, fits: number) => (fits ? `${open} opportunities are open right now; ${fits} match your interests.` : `${open} opportunities are open right now.`),
    saved: 'Saved',
    applied: 'Applied',
    accepted: 'Accepted',
    closing: 'Closing this week',
    upcoming: 'Upcoming deadlines',
    upcomingSub: 'Saved opportunities you haven’t applied to yet',
    upcomingEmpty: 'Save an opportunity you like — its deadline will show up here and we’ll remind you.',
    allTracked: 'See all',
    prep: (done: number, total: number) => `Prep ${done}/${total}`,
    findCta: 'Find opportunities',
    calendarCta: 'Calendar',
    closingTitle: 'Closing soon',
    closingSub: 'In your interests, closing within 14 days, not saved yet',
    shortcutsTitle: 'Shortcuts',
    guidesSub: 'Programmes and how to apply',
    aiSub: 'Letters and application review',
    greet: (part: 'morning' | 'day' | 'evening', name: string) =>
      `${part === 'morning' ? 'Good morning' : part === 'day' ? 'Good afternoon' : 'Good evening'}${name ? `, ${name}` : ''}`,
    nextTitle: 'Next deadline',
    nextDays: (d: number) => (d === 0 ? 'Today!' : d === 1 ? 'Tomorrow' : `${d} days`),
    nextLeft: 'left',
    nextSaved: 'Saved by you',
    nextSuggested: 'A match for you',
    nextNone: 'No deadlines coming up. Browse new opportunities.',
    weekTitle: 'Next 14 days',
    weekSub: 'How many deadlines fall on each day. Orange — ones you saved.',
    planTitle: 'This week’s plan',
    planSub: 'The prep steps left for your saved opportunities — tick them off here.',
    planReady: 'Prep done — time to apply!',
    planApply: 'Apply',
    planEmpty: 'Save an opportunity you like — its prep steps will show up here as a plan.',
    programsTitle: 'Programmes',
    programsOpen: (n: number) => (n ? `${n} open` : 'Nothing open right now'),
    guidesTitle: 'Guides',
    badgesTitle: 'Your achievements',
    badgesMore: 'See all',
    profileStrength: (p: number) => `Profile ${p}%`,
  },
  notes: {
    title: 'My notes',
    sub: 'Notes only you can see: ideas, reminders, application plans.',
    ph: 'Write a new note… (e.g. “Friday: go to ASAN for the passport”)',
    add: 'Add',
    empty: 'No notes yet. Write your first one above.',
    pin: 'Pin',
    unpin: 'Unpin',
    edit: 'Edit',
    remove: 'Delete',
    confirmRemove: 'Delete this note?',
    save: 'Save',
    cancel: 'Cancel',
    color: 'Colour',
    limit: 'You can keep up to 100 notes. Delete an old one first.',
    seeAll: 'All notes',
    count: (n: number) => `${n} note${n === 1 ? '' : 's'}`,
  },
  map: {
    title: 'Map',
    sub: 'Opportunities by country. Tap a country to see what’s open there.',
    allCountries: 'All countries',
    online: 'Online',
    count: (n: number) => `${n} opportunit${n === 1 ? 'y' : 'ies'}`,
    countries: (n: number) => `${n} countr${n === 1 ? 'y' : 'ies'}`,
    hint: 'Tap a country to see what’s open',
    kindLabel: 'Map type',
    kinds: { standard: 'Standard', terrain: 'Terrain', satellite: 'Satellite', clean: 'Simple' },
    empty: 'Nothing open in this country right now.',
    openList: 'Open in the list',
    noKey: 'The map isn’t connected yet. Pick a country from the list below.',
    loadError: 'The map couldn’t load. Pick a country from the list below.',
    pick: 'Pick a country',
  },
  feed: {
    searchTitle: 'What are you looking for today?',
    searchPh: 'E.g. youth exchange, Italy, environment…',
    searchBtn: 'Search',
    tabs: { forYou: 'For you', latest: 'Just added', closing: 'Closing soon' },
    featured: 'Opportunity of the day',
    empty: 'Nothing here yet.',
    myDeadlines: 'My deadlines',
    myDeadlinesEmpty: 'Deadlines of the opportunities you save will show up here.',
    countries: 'By country',
    tips: 'Useful tips',
    links: { profile: 'My profile', cv: 'My CV', tracker: 'My applications' },
    aiSub: 'Letter drafts and application review',
    aiOpen: 'Open the AI assistant',
  },
  home: {
    weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    brief: {
      lead: 'This week you have',
      deadlines: (n: number) => `${n} deadline${n === 1 ? '' : 's'}`,
      mid: 'and',
      fresh: (n: number) => `${n} new match${n === 1 ? '' : 'es'}`,
      end: 'for your interests.',
      calm: 'A quiet week — a good time to look at new opportunities.',
    },
    profileRing: (p: number) => `Profile ${p}%`,
    deck: {
      title: 'Discover',
      sub: 'Opportunities that fit you, one at a time. Save what you like, skip the rest.',
      skip: 'Skip',
      save: 'Save',
      more: 'Details',
      count: (i: number, n: number) => `${i} / ${n}`,
      doneTitle: 'You’ve seen them all 🎉',
      doneSub: 'New opportunities will show up here as they’re added.',
      reset: 'Show skipped again',
      browse: 'All opportunities',
    },
    countdown: { title: 'Next deadline', none: 'No saved deadlines.', noneCta: 'Save an opportunity' },
    pipeline: { title: 'My application path', rejected: (n: number) => `${n} rejected — that’s experience too 💪` },
    todo: { title: 'Next steps', sub: 'Prep for your saved opportunities — tick them off here', empty: 'No prep tasks. Save an opportunity — its steps will show up here.' },
    timeline: { title: 'Next 60 days', sub: 'Orange — saved by you, green — good matches.', today: 'Today' },
    programs: 'Programmes',
    guides: 'Worth a read',
    searches: 'Your searches',
  },
  start: {
    title: 'Getting started',
    sub: (d: number, t: number) => `${d}/${t} done — the way to get the most out of Openly`,
    done: 'All set! 🎉',
    hide: 'Hide',
    steps: {
      interests: 'Pick your interests',
      profile: 'Add a photo and a headline',
      about: 'Write your “About me” for the AI',
      save: 'Save your first opportunity',
      search: 'Save a search',
      applied: 'Mark one application as applied',
    },
  },
  aiHub: {
    title: 'AI application assistant',
    sub: 'Build your motivation letter from your own story and check it with a committee’s eye before you send it.',
    statusActive: 'Active',
    statusSoon: 'Coming soon',
    statusLocked: 'Used up today',
    statusChecking: 'Checking…',
    perDay: (n: number) => `${n} uses a day`,
    letterTitle: 'Motivation letter assistant',
    letterPoints: ['Asks 4–6 questions tailored to the call', 'Builds the outline only from your answers', 'No invented facts — gaps stay in [brackets]'],
    reviewTitle: 'Application review',
    reviewPoints: ['Upload your letter or CV (PDF, DOCX) or paste it', 'A 1–10 fit score and your strengths', 'Concrete fixes: quote → problem → suggestion'],
    pickTitle: 'Which opportunity?',
    pickSub: 'The AI always works with a specific call. Pick one of your saved opportunities.',
    pickEmpty: 'You haven’t saved anything yet. Save an opportunity you like, then prepare with the AI here.',
    pickFind: 'Browse opportunities',
    write: 'Write letter',
    review: 'Review',
    howTitle: 'How it works',
    how: [
      { title: 'Pick an opportunity', text: 'The AI reads the call’s topic, requirements and deadline.' },
      { title: 'Answer the questions', text: 'Write your real experience — the AI never invents facts for you.' },
      { title: 'Review and send', text: 'Rewrite the draft in your own voice, then have the AI check it.' },
    ],
    aboutTitle: 'How well does the AI know you?',
    aboutEmpty: 'Your “About me” is empty. Add your studies, experience and languages — questions and feedback get much sharper.',
    aboutFilled: (n: number) => `“About me” is filled in (${n} characters). The AI tailors its questions and feedback to it.`,
    aboutCta: 'Update profile',
    lockedTitle: 'Free plan: 1 AI use a day',
    lockedText: 'One letter draft or one review a day is free. Premium gives you 15 a day — 3 ₼ / month.',
    lockedCta: 'See Premium',
    dashCta: 'Open the AI assistant',
    dashNext: (title: string) => `Next: a letter for “${title}”`,
  },
  student: {
    title: 'Student',
    hubTitle: 'Study abroad',
    hubSub: 'Scholarships, universities, an application roadmap and your own plan — in one place.',
    badge: '7 ₼ / mo',
    tabs: { roadmap: 'Roadmap', scholarships: 'Scholarships', universities: 'Universities', plan: 'My plan', ai: 'AI advisor' },
    lockTitle: 'Openly Student — your way to studying abroad',
    lockSub: 'For anyone who wants a bachelor’s or master’s abroad: which scholarship, which university, when and how to apply.',
    lockItems: (sch: number, uni: number) => [
      `${sch} scholarships: who they’re for, what they cover, deadlines`,
      `${uni} universities: fields, tuition, application fees, requirements`,
      'A 16-step application roadmap — track your progress',
      'My plan: universities that fit your score and budget, side-by-side comparison, saved scholarships and deadlines',
      'AI advisor: scholarships and universities that fit you, essay feedback',
    ],
    lockCta: 'Get the Student plan on WhatsApp',
    lockNote: 'Message us on WhatsApp at 070 903 40 41 — we’ll switch the plan on for your account after payment.',
    waMessage: (email: string) => `Hi! I’d like the Openly Student plan (7 ₼ / month). My account: ${email}`,
    lockGuest: 'Sign up for free first',
    loadError: 'Couldn’t load the data.',
    backToHub: 'Back to the student section',
    profileTitle: 'My profile',
    profileSub: 'Your name, photo and a short background. The AI advisor reads your “About me”.',
    aboutHint: 'Your studies, grades and scores, experience and goal — the AI advisor bases its advice on this.',
    aboutPh: 'E.g. ADA University, computer science, 3rd year. GPA 3.6, IELTS 7.0. I want a master’s in data science in Germany.',
    planTitle: 'My plan',
    planActive: 'Student plan is active 🎓',
    planActiveSub: 'Scholarships, universities, the roadmap, the planner and the AI advisor are open.',
    planLocked: 'Student plan isn’t active',
    planLockedSub: 'Once the plan is on, scholarships, universities, the planner and the AI advisor open up.',
    planSeeInside: 'See what’s inside',
    cancelPlan: 'Cancel the Student plan',
    cancelPlanSub: 'Your roadmap progress and saved items stay, but the catalogue and the AI close.',
    cancelPlanConfirm: 'Cancel the Student plan? Scholarships, universities and the AI advisor will close.',
    planCancelled: 'Student plan cancelled.',
    progress: (d: number, t: number) => `${d}/${t} steps done`,
    phaseDone: (d: number, t: number) => `${d} of ${t} done`,
    youAreHere: 'You are here',
    nextUp: 'Next up',
    allDone: 'All done — good luck!',
    open: 'Open',
    savedCount: (n: number) => `${n} scholarship${n === 1 ? '' : 's'} saved`,
    search: 'Search by name or country',
    filters: 'Filters',
    openNow: 'Open now',
    forMe: 'Fits me',
    forMeHint: 'Set your level, field and budget in “My plan” and we’ll mark what fits you.',
    sort: 'Sort',
    sortDeadline: 'Soonest deadline',
    sortName: 'Name',
    sortCost: 'Lowest cost',
    results: (n: number) => `${n} result${n === 1 ? '' : 's'}`,
    covers: { tuition: 'Tuition', stipend: 'Monthly stipend', housing: 'Housing', flights: 'Flights', insurance: 'Insurance', language: 'Language course' },
    fullFunding: 'Fully funded',
    partialFunding: 'Partly funded',
    closesToday: 'Closes today',
    openUntil: (m: string) => `Open · usually closes in ${m}`,
    closesIn: (m: string) => `Usually closes in ${m}`,
    opensIn: (m: string) => `Opens in ${m}`,
    datesVary: 'Dates vary — see details',
    fitsYou: 'Fits you',
    misses: { level: 'Not for your level', field: 'Not for your field', budget: 'Over your budget' },
    save: 'Save',
    saved: 'Saved',
    details: 'Details',
    keyFacts: 'Key facts',
    compare: 'Compare',
    compareN: (n: number) => `Compare (${n})`,
    compareMax: 'You can compare up to 3 universities',
    compareTitle: 'Compare universities',
    compareClear: 'Clear selection',
    place: 'Location',
    language: 'Taught in',
    from: (x: string) => `from ${x}`,
    best: 'Best value',
    auto: 'Automatic',
    autoHint: {
      goal: 'Done when you pick your level and field in “My plan”',
      language: 'Done when you enter your IELTS score in “My plan”',
      budget: 'Done when you set your yearly budget in “My plan”',
      shortlist: 'Done when 5 universities are on your list',
      scholarships: 'Done when you save at least one scholarship',
      submit: 'Done when something on your list is marked “Applied”',
      decide: 'Done when something on your list is marked “Accepted”',
    } as Record<string, string>,
    manualHint: 'Tick this yourself',
    aiSub: 'Based on your details and our catalogue. Check the official page before you decide.',
    aiModes: { plan: 'My plan', ask: 'Ask a question', review: 'Review my essay' },
    aiModeDesc: { plan: 'Scholarships, universities and steps that fit you', ask: 'Questions about studying and applying abroad', review: 'Feedback on your letter for a chosen place' },
    aiLastPlan: (when: string) => `Last plan · ${when}`,
    aiYou: 'You',
    aiPlanIntro: 'From your level, field, IELTS, budget and the “About me” text in your profile, we pick the scholarships and universities in our catalogue that fit you and lay out your next steps month by month.',
    aiPlanBtn: 'Build my plan',
    aiAgain: 'Again',
    aiNeedPrefs: 'For a sharper result, first fill in your level, field, IELTS and budget in “My plan”.',
    aiRecSch: 'Recommended scholarships',
    aiRecUni: 'Recommended universities',
    aiSteps: 'Next steps',
    aiRisks: 'Watch out for',
    aiAskIntro: 'Ask anything about studying abroad, scholarships or applications.',
    aiAskPh: 'Type your question…',
    aiAskBtn: 'Ask',
    aiExamples: ['Can I do a master’s in Europe with IELTS 6.0?', 'Which scholarships cover tuition in full?', 'When should I start my motivation letter?'],
    aiRelated: 'See in the catalogue',
    aiFollowUp: 'You could also ask',
    aiReviewIntro: 'Paste your motivation letter or essay — we’ll review it against the requirements of the scholarship or university you choose.',
    aiReviewFor: 'Who is it for?',
    aiReviewGeneral: 'General (no specific place)',
    aiFitBtn: 'AI: do I fit?',
    aiFitTitle: 'AI check',
    aiVerdicts: { likely: 'You very likely fit', maybe: 'Possibly — check', unlikely: 'Looks unlikely' } as Record<string, string>,
    aiPrepare: 'What to prepare',
    aiCheck: 'Confirm on the official page',
    aiStudentOnly: 'The AI advisor is part of the Student plan.',
    allFields: 'All fields',
    allCountries: 'All countries',
    allLevels: 'All levels',
    anyField: 'Any field',
    coverage: 'What it covers',
    eligibility: 'Who can apply',
    howToApply: 'How to apply',
    deadline: 'Deadline',
    officialPage: 'Official page',
    noResults: 'Nothing matches these filters.',
    tuition: 'Tuition',
    perYear: '/yr',
    living: 'Living',
    perMonth: '/mo',
    appFee: 'Application fee',
    free: 'Free',
    unknown: 'Depends on programme',
    exams: 'Exams',
    requirements: 'Requirements',
    scholarshipsNote: 'Scholarships',
    addShortlist: 'Add to my list',
    inShortlist: 'On my list',
    disclaimer: 'Amounts and dates are estimates and change every year — check the official page before applying.',
    myInfo: 'About me',
    myInfoSub: 'We use this to mark the scholarships and universities that fit you. Saved to your profile.',
    notSet: 'Not set',
    level: 'Level',
    field: 'Field',
    ielts: 'Your IELTS score',
    noIelts: 'Not yet',
    budget: 'Yearly budget',
    yearCost: 'Estimated yearly cost',
    needIelts: (n: number) => `Needs IELTS ${n}`,
    fitUnis: 'Universities that fit you',
    fitSch: 'Scholarships that fit you',
    upcomingTitle: 'Upcoming deadlines',
    upcomingEmpty: 'Save scholarships and add universities to your list — their deadlines will show up here.',
    myList: 'My list',
    listEmptySch: 'You haven’t saved any scholarships yet.',
    listEmptyUni: 'You haven’t added any universities yet.',
    feesTotal: 'Application fees in total',
    firstYear: 'Estimated first-year cost',
    remove: 'Remove from list',
    statuses: { planning: 'Planning', applied: 'Applied', accepted: 'Accepted', rejected: 'Rejected' },
  },
  searches: {
    title: 'Your saved searches',
    save: 'Save this search',
    namePh: 'Search name',
    saveBtn: 'Save',
    cancel: 'Cancel',
    saved: 'Saved — the search will show up on your home page.',
    limit: 'You can save up to 10 searches. Delete an old one and try again.',
    matches: (n: number) => `${n} opportunit${n === 1 ? 'y' : 'ies'}`,
    fresh: (n: number) => `${n} new`,
    remove: 'Delete search',
    fallbackName: 'My search',
  },
  complete: {
    title: (p: number) => `Your profile is ${p}% complete`,
    sub: 'A full profile helps us pick opportunities that fit you and helps the AI assistant draft a better letter.',
    items: { photo: 'Photo', interests: 'Interests', country: 'Country', headline: 'Headline', about: 'About me', studies: 'Studies / work', languages: 'Languages' },
    cta: 'Complete your profile',
  },
  newHere: 'New here? Read our short guides on the programmes and how to apply.',
  prep: {
    title: 'Application prep',
    items: {
      cv: 'CV is ready',
      letter: 'Motivation letter written',
      passport: 'Passport validity checked',
      sending_org: 'Contacted the sending organisation',
      form: 'Application form filled in',
    },
    note: 'My notes',
    notePh: 'E.g. "Emailed the organisation on Monday, waiting for a reply"',
    noteSaved: 'Saved ✓',
  },
  trip: {
    title: 'Getting ready for the trip',
    items: {
      infopack: 'Info pack read, replied to the organiser',
      visa: 'Visa documents submitted / visa received',
      insurance: 'Travel insurance bought',
      tickets: 'Tickets bought, receipts kept (for the refund)',
      youthpass: 'Get the Youthpass certificate at the end',
    },
  },
  age: {
    ok: (range: string) => `Your age fits this kind of programme (usually ${range}).`,
    young: (range: string) => `Heads-up: this kind of programme is usually for ages ${range} — check the call.`,
    old: (range: string) => `Heads-up: this kind of programme is usually for ages ${range} — check the call.`,
    unknown: (range: string) => `This kind of programme is usually for ages ${range}. Add your year of birth to your profile and we’ll check it for you.`,
    plus: (min: number) => `${min}+`,
  },
  similar: {
    title: 'Similar opportunities',
  },
  list: {
    title: 'Opportunities',
    allTitle: 'All opportunities',
    picked: 'Picked for you',
    seeAll: 'See all',
    filters: 'Filters',
    sub: (n: number) => `${n} open opportunit${n === 1 ? 'y' : 'ies'}`,
    results: (n: number) => `${n} result${n === 1 ? '' : 's'}`,
    search: 'Search by title, program or country…',
    forYou: 'My interests',
    allPrograms: 'All programs',
    allKinds: 'All types',
    allCountries: 'All countries',
    online: 'Online',
    closingSoon: 'Closing in 7 days',
    fullyFunded: 'Funded',
    showClosed: 'Show closed ones too',
    clear: 'Clear filters',
    empty: 'No opportunities match these filters.',
    noInterests: 'Pick your interests and we’ll highlight matching opportunities.',
    pickInterests: 'Pick interests',
    draft: 'Draft',
    earlyTeaser: (n: number) => `Premium users already see ${n} new opportunit${n === 1 ? 'y' : 'ies'}. You’ll see ${n === 1 ? 'it' : 'them'} in 24 hours.`,
    seePremium: 'See Premium',
    premiumFilter: 'This filter is Premium',
    newBadge: 'New',
    sortBest: 'Best match',
    sortDeadline: 'Deadline',
    match: (n: number) => `${n}% match`,
    matchReasons: { interests: 'matches your interests', funded: 'fully funded', partlyFunded: 'partly funded', online: 'online', country: 'in your country', kind: 'a type you like', destination: 'a country on your list' },
    forYouTitle: (n: number) => (n === 1 ? '1 new opportunity for you' : `${n} new opportunities for you`),
    forYouSoon: (d: number) => (d <= 0 ? 'one closes today' : d === 1 ? 'one closes tomorrow' : `one closes in ${d} days`),
  },
  card: { save: 'Save', saved: 'Saved', closed: 'Closed', deadline: 'Deadline' },
  detail: {
    notFound: 'Opportunity not found or no longer available.',
    apply: 'Apply on the official page',
    applyHint: 'You apply at the official source. Update the status here after applying.',
    track: 'Add to my applications',
    remove: 'Remove from list',
    status: 'Status',
    about: 'About',
    when: 'Dates',
    where: 'Location',
    type: 'Type',
    costs: 'Costs',
    program: 'Program',
    organizer: 'Organizer',
    interests: 'Topics',
    sendingOrg: 'Sending organisation in Azerbaijan',
    sendingOrgHint: 'You apply through this organisation, not directly. Contact:',
  },
  tracker: {
    title: 'My applications',
    sub: 'Everything you saved and applied to, in one place.',
    all: 'All',
    empty: 'You haven’t saved anything yet.',
    emptyCta: 'Browse opportunities',
    usage: (n: number) => `Free plan: ${n} / ${FREE_EVENT_LIMIT} opportunities`,
    upgrade: 'Unlimited tracking with Premium — 3 ₼ / mo',
    confirmRemove: (title: string) => `Remove “${title}” from your list? Its prep checklist and notes will be deleted too.`,
  },
  limit: {
    title: 'Free plan limit',
    text: `On the free plan you can track ${FREE_EVENT_LIMIT} opportunities at a time. Remove one to add another, or upgrade to Premium.`,
    ok: 'Got it',
    manage: 'Go to my applications',
  },
  profile: {
    title: 'Profile',
    onboardingTitle: 'Let’s get to know you 👋',
    onboardingSub: 'Pick your interests so we can put matching opportunities first. You can change them later.',
    name: 'Full name',
    email: 'Email',
    country: 'Country you live in',
    countryPh: 'Select…',
    interests: 'Interest areas',
    interestsHint: 'Pick as many as you like',
    plan: 'Plan',
    basic: 'Free',
    premium: 'Premium',
    student: 'Student',
    save: 'Save',
    continue: 'Continue',
    saved: 'Saved ✓',
    about: 'About me',
    aboutHint: 'Education, experience, skills, volunteering background. The AI assistant uses this when drafting letters.',
    aboutPh: 'E.g.: ADA University, 3rd year, international relations. 2 years volunteering at a youth centre, organised environmental campaigns. English B2.',
    photo: 'Profile photo',
    changePhoto: 'Change photo',
    removePhoto: 'Remove',
    photoHint: 'JPG, PNG or WEBP. Cropped to a square.',
    photoError: 'Couldn’t upload the photo. Try another one (JPG, PNG, WEBP).',
    headline: 'Headline',
    headlinePh: 'E.g. Student · ADA University · Environmental volunteer',
    tabProfile: 'Profile',
    tabPremium: 'Plan',
    tabSettings: 'Settings',
    security: 'Change password',
    securityHint: 'If you sign in with Google, you can also set a password here for email sign-in.',
    notifications: 'Email notifications',
    digest: 'New opportunities digest',
    digestFree: 'Once a week (Monday) — new opportunities matching your interests.',
    digestPremium: 'Every day — new opportunities matching your interests.',
    reminders: 'Deadline reminders',
    remindersPremium: 'When a saved opportunity closes in 7, 3 and 1 days.',
    remindersFree: 'Premium only. Premium — 3 ₼ / mo.',
    sectionBasics: 'Basics',
    sectionBasicsSub: 'How other participants and the AI see you.',
    sectionInterests: 'Interests',
    sectionInterestsSub: (n: number) => (n ? `${n} selected — picks and the email digest follow these.` : 'We bring opportunities in these areas to the front.'),
    sectionAbout: 'About me, for the AI',
    sectionAboutSub: 'The AI assistant tailors its questions and feedback to this text. The more specific, the better.',
    aboutCount: (n: number) => `${n} / 2000`,
    aboutTipsLabel: 'Add:',
    aboutTips: [
      { label: 'Studies', text: 'Studies: ' },
      { label: 'Experience', text: 'Volunteering / work experience: ' },
      { label: 'Languages', text: 'Languages: ' },
      { label: 'Skills', text: 'Skills: ' },
      { label: 'Goal', text: 'Why I want to join international programmes: ' },
    ],
    unsaved: 'You have unsaved changes',
    statSaved: 'saved',
    statApplied: 'applied',
    statAccepted: 'accepted',
    completeness: (p: number) => `Profile ${p}% complete`,
    language: 'Language',
    languageSub: 'The language of the site.',
    account: 'Account',
    accountEmail: 'Email',
    accountType: 'Account type',
    accountRegular: 'Regular account',
    accountStudent: 'Student account',
    logout: 'Log out',
    logoutSub: 'You’ll be signed out on this device.',
    tabJourney: 'My journey',
    tabMatch: 'Preferences',
    theme: 'Profile colour',
    birthYear: 'Year of birth',
    birthYearHint: 'to check age limits',
    birthYearPh: 'Choose…',
    occupation: 'Right now',
    occupations: { school: 'At school', student: 'A student', graduate: 'A graduate', working: 'Working', other: 'Other' },
    school: 'School / university / workplace',
    schoolPh: 'E.g. ADA University',
    field: 'Field of study / work',
    fieldPh: 'E.g. International relations',
    linkedin: 'LinkedIn (optional)',
    sectionLanguages: 'Languages',
    sectionLanguagesSub: 'Most programmes run in English — be honest about your level.',
    languageName: 'Language',
    languagePh: 'E.g. English',
    languageLevel: 'Level',
    levelNative: 'Native',
    addLanguage: 'Add a language',
    languageSuggestions: ['Azerbaijani', 'English', 'Russian', 'Turkish', 'German', 'French', 'Spanish', 'Italian'],
    sectionSkills: 'Skills',
    sectionSkillsSub: 'Used in your CV and in AI feedback. Press Enter to add.',
    skillPh: 'Type a skill and press Enter…',
    skillSuggestions: ['Teamwork', 'Leadership', 'Public speaking', 'Project management', 'Event planning', 'Photography', 'Video editing', 'Graphic design', 'Social media', 'Translation'],
    sectionExperience: 'Experience',
    sectionExperienceSub: 'Past exchanges, volunteering, projects. The ones abroad become stamps in your passport.',
    expTitle: 'What was it?',
    expTitlePh: 'E.g. Youth exchange “Green Minds”',
    expOrg: 'Organisation',
    expYear: 'Year',
    expCountry: 'Country',
    addExperience: 'Add experience',
    remove: 'Remove',
  },
  prefsTab: {
    title: 'What suits you?',
    sub: 'These choices shape “Picked for you”, the fit score and recommendations. Every change is saved right away.',
    kinds: 'Which types interest you?',
    kindsHint: 'Pick none to see all.',
    duration: 'Duration',
    durations: { short: 'Short', long: 'Long', any: 'Either' },
    durationsSub: { short: '5–21 days: exchanges, courses', long: '2–12 months: volunteering', any: 'Both' },
    funded: 'Only fully funded',
    fundedSub: 'Others move down in recommendations.',
    passport: 'I have a valid passport',
    passportSub: 'If not, we’ll remind you while you prepare an application.',
    destinations: 'Countries you’d like to go to',
    destinationsHint: 'Opportunities there move up.',
    saved: 'Saved ✓',
  },
  journey: {
    statsTitle: 'My applications in numbers',
    total: 'Applications',
    accepted: 'Accepted',
    rate: 'Acceptance rate',
    badgesTitle: 'Achievements',
    badgesSub: (n: number, t: number) => `${n} of ${t} earned`,
    badges: {
      first_save: { name: 'First step', how: 'Save your first opportunity' },
      first_apply: { name: 'Brave', how: 'Send your first application' },
      five_apply: { name: 'Determined', how: 'Send 5 applications' },
      accepted: { name: 'Accepted!', how: 'Get accepted to a programme' },
      profile: { name: 'Complete profile', how: 'Fill in your profile 100%' },
      polyglot: { name: 'Polyglot', how: 'Add 3 or more languages' },
      traveller: { name: 'Traveller', how: 'Take part in 3 countries' },
      resilient: { name: 'Resilient', how: 'Keep going after a rejection' },
    },
    passportTitle: 'My travel passport',
    passportSub: 'Countries of the programmes you were accepted to and of your experience.',
    passportEmpty: 'No stamps yet. Programmes you’re accepted to and experience abroad (under “Experience”) will show up here.',
    cvTitle: 'Your volunteer CV',
    cvSub: 'Built from your profile: studies, languages, skills, experience. Save it as a PDF and attach it to applications.',
    cvCta: 'View CV',
  },
  cv: {
    title: 'Volunteer CV',
    back: 'Back to profile',
    print: 'Save as PDF / print',
    printHint: 'Choose “Save as PDF” in the print dialog.',
    edit: 'Edit profile',
    empty: 'Not much for a CV yet. Add your studies, languages, skills and experience in your profile.',
    contact: 'Contact',
    about: 'About me',
    education: 'Studies / occupation',
    languages: 'Languages',
    skills: 'Skills',
    experience: 'Experience',
    openly: 'Programmes I was accepted to via Openly',
    interests: 'Interests',
    born: (y: number) => `Born ${y}`,
  },
  guest: {
    listBanner: 'Sign up for free: save opportunities, track your applications, see what fits you.',
    signUp: 'Sign up',
    logIn: 'Log in',
    sidebar: 'Create a free account to save opportunities and track your applications.',
    aiText: 'The AI application assistant is for account holders: 1 use a day on the free plan, 15 with Premium. Sign up for free first.',
  },
  share: {
    title: 'Share',
    copy: 'Copy link',
    copied: 'Copied ✓',
    calendar: 'Add the deadline to your calendar',
    google: 'Google Calendar',
    ics: 'Apple / Outlook (.ics)',
    eventTitle: (title: string) => `Deadline: ${title}`,
    text: (title: string, date: string) => `${title} — deadline ${date}`,
  },
  applied: {
    question: 'Did you apply?',
    text: 'If so, let’s mark it as "Applied" so it’s easy to track.',
    yes: 'Yes, I applied',
    no: 'Not yet',
  },
  peers: {
    title: 'Other accepted participants',
    sub: 'Meet the others accepted to the same programme: plan travel, visas and accommodation together.',
    share: 'Share my name and email with others accepted to this programme',
    none: 'Nobody else has shared their contact yet. They’ll show up here as soon as they do.',
  },
  ai: {
    title: 'AI application assistant',
    sub: 'Build your motivation letter from your own story and check it before you send.',
    open: 'Open AI assistant',
    locked: 'Free plan: 1 AI use a day. Premium gives you 15.',
    tabLetter: 'Motivation letter',
    tabReview: 'Review my application',
    tabLetterShort: 'Letter',
    tabReviewShort: 'Review',
    comingSoon: 'The AI assistant is launching soon. Everything is in place — you’ll be able to use it right here.',
    letterIntro: 'The AI doesn’t write a ready-made letter. It first asks you questions tailored to this opportunity, then builds a letter outline only from your answers. You write the final words.',
    start: 'Get my questions',
    thinking: 'The AI is thinking…',
    answerPh: 'Be concrete: what you did, where, what you learned…',
    letterLang: 'Letter language',
    makeDraft: 'Build a draft',
    needAnswers: 'Answer at least one question.',
    draftTitle: 'Draft',
    draftNote: 'This is a starting point. Fill in the [bracketed] parts and rewrite it in your own voice — committees spot template letters fast.',
    copy: 'Copy',
    copied: 'Copied ✓',
    tips: 'Before you send',
    missing: 'Information to add',
    again: 'Start over with AI',
    writeMyself: 'I’ll write it myself',
    myLetter: 'My motivation letter',
    letterPh: 'Write or paste your letter here…',
    saveLetter: 'Save',
    unsaved: 'You have unsaved changes',
    savedAt: (when: string) => `Saved · ${when}`,
    reviewIntro: 'Upload your letter or CV as a file, or paste its text. The AI compares it with this opportunity’s requirements and gives concrete feedback.',
    docType: 'Document',
    docLetter: 'Motivation letter',
    docCv: 'CV',
    reviewPh: 'Paste the text here (at least 50 characters)…',
    upload: 'Upload a file',
    uploadHint: 'PDF, DOCX or TXT, up to 3 MB. Or paste the text below.',
    fromFile: (name: string) => `Text taken from "${name}" — you can edit it before sending.`,
    pdfAttached: 'The PDF is reviewed as-is (layout and scanned pages included).',
    removeFile: 'Remove file',
    fileType: 'This file type isn’t supported. Choose PDF, DOCX or TXT (save an old .doc as .docx in Word).',
    fileTooBig: 'The file is too large (max 3 MB).',
    fileRead: 'Couldn’t read the file. Choose another one or paste the text.',
    reviewBtn: 'Review',
    tooShort: 'The text is too short (at least 50 characters).',
    score: 'Fit score',
    strengths: 'Strengths',
    issues: 'What to fix',
    suggestion: 'Suggestion',
    missingTitle: 'The committee will look for this',
    remaining: (n: number) => `${n} AI uses left today`,
    quota: (r: number, l: number) => `${r} of ${l} AI uses left today`,
    freeNote: 'Free plan: 1 a day. Premium gives you 15 a day →',
    errors: {
      premium_required: 'The AI assistant isn’t available for this account.',
      student_required: 'The AI advisor is part of the Student plan.',
      daily_limit: 'You’ve reached today’s AI limit (free: 1 a day, Premium: 15). Try again tomorrow.',
      refused: 'The AI couldn’t process this request. Change the text and try again.',
      ai_unavailable: 'The AI assistant isn’t available right now. Try again in a bit.',
      not_configured: 'The AI assistant is launching soon.',
      unknown: 'Something went wrong. Please try again.',
    },
  },
  premium: {
    title: 'Premium',
    sub: 'For people who don’t want to miss a single opportunity.',
    current: 'Your plan',
    active: 'Premium is active ✦',
    free: 'Free',
    price: '3 ₼ / mo',
    feature: 'Feature',
    rows: [
      { name: 'Opportunity list, search, interest and country filters', free: true, premium: true },
      { name: 'Opportunities tracked at a time', free: '3', premium: 'Unlimited' },
      { name: 'New-opportunity email digest', free: 'Weekly', premium: 'Daily' },
      { name: 'Early access to new opportunities (24 hours earlier)', free: false, premium: true },
      { name: 'Advanced filters: funded, closing in 7 days', free: false, premium: true },
      { name: 'Deadline reminders (7, 3, 1 days before)', free: false, premium: true },
      { name: 'Smart matching: a fit score for every opportunity', free: false, premium: true },
      { name: 'AI assistant: letter drafts and application review', free: '1 a day', premium: '15 a day' },
    ],
    cta: 'Get Premium on WhatsApp',
    ctaNote: 'Message us on WhatsApp at 070 903 40 41 — we’ll switch Premium on for your account after payment.',
    waMessage: (email: string) => `Hi! I’d like Openly Premium (3 ₼ / month). My account: ${email}`,
    activeSub: 'All Premium features are on: unlimited tracking, early access, reminders, smart matching and the AI assistant.',
    cancelTitle: 'Cancel Premium',
    cancelSub: 'You’ll move to the free plan. Your saved opportunities stay, but you can only track up to 3 new ones.',
    cancelBtn: 'Cancel Premium',
    cancelConfirm: 'Cancel Premium? The AI assistant, reminders and unlimited tracking will be switched off.',
    cancelled: 'Premium cancelled. You’re on the free plan now.',
    studentActive: 'Student plan is active 🎓',
    studentActiveSub: 'All Premium features plus the student section are on: scholarships, universities, the roadmap and the planner.',
    openStudent: 'Open the student section',
    studentUpsellTitle: 'Want to study abroad? Openly Student — 7 ₼ / mo',
    studentUpsellText: 'Everything in Premium, plus scholarships, universities (fields, tuition and application fees), a 16-step roadmap and a cost planner.',
    studentUpsellCta: 'See what’s inside',
  },
  users: {
    title: 'Users',
    sub: (n: number, p: number, st: number) => `${n} users · ${p} Premium · ${st} Student`,
    confirmPlan: (email: string, plan: string) => `Move ${email} to the ${plan} plan?`,
    planLabel: 'Plan',
    typeLabel: 'Account type',
    typeRegular: 'Regular',
    typeStudent: 'Student',
    confirmType: (email: string, type: string) => `Make ${email} a ${type} account? A plan this type doesn’t have goes back to free.`,
    search: 'Search by name or email…',
    joined: 'Joined',
    admin: 'Admin',
    empty: 'No users found.',
  },
  admin: {
    title: 'Manage opportunities',
    sub: 'Add, edit, publish or hide.',
    add: 'New opportunity',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: (title: string) => `Delete “${title}”? This can’t be undone.`,
    published: 'Published',
    draft: 'Draft',
    empty: 'No opportunities yet. Add the first one.',
    newTitle: 'New opportunity',
    editTitle: 'Edit opportunity',
    f: {
      title: 'Title',
      program: 'Program',
      otherProgram: 'Program name',
      organizer: 'Organizer',
      sendingOrg: 'Sending organisation (AZ)',
      sendingOrgHint: 'For youth exchanges: applications go through this organisation.',
      sendingOrgContact: 'Sending organisation contact (email, phone or website)',
      kind: 'Type',
      country: 'Country',
      city: 'City',
      online: 'Takes place online',
      interests: 'Topics',
      deadline: 'Application deadline',
      start: 'Start date',
      end: 'End date',
      costs: 'Costs',
      url: 'Official link',
      description: 'Description',
      publish: 'Publish (visible to users)',
      save: 'Save',
      cancel: 'Cancel',
      required: 'This field is required.',
      badUrl: 'The link must start with https://',
      badDates: 'End date can’t be before the start date.',
    },
  },
  daysLeft: (d: number) => (d < 0 ? 'Closed' : d === 0 ? 'Closes today' : d === 1 ? 'Closes tomorrow' : `${d} days left`),
};

export const appText = { az, en };

export function useAppText() {
  const { lang } = useLang();
  return { tx: appText[lang], lang };
}
